### DISCUSSION TITLE
Working with service name but not with ingress over https

### DISCUSSION THREAD

**Discussion by tutaidalal** [jacksontj/promxy#619] [Q&A] [answered]
Hi I tried to configure multiple prom endpoints using service name in kubernetes, it worked. However whenever I am trying to use ingress instead of service as I want to get the data from another cluster, its not showing any matrices. 

I have enable debug log and i can see that te http call is returning success, still no data found. Can someone put some light to help me.

Config:
 server_groups:
      - anti_affinity: 10s
        http_client:
          tls_config:
            insecure_skip_verify: true
        ignore_error: true
        labels:
          source: nb1-federation
        path_prefix: <path>
        scheme: https
        static_configs:
        - targets:
          - <my-ingress-name>

HTTP Call Log - 

time="2023-10-05T05:14:16Z" level=debug msg="https://<my-ingress-name>/<path>" api=Query query=node_network_name_assign_type ts="2023-10-05 05:14:12.863 +0000 UTC"
time="2023-10-05T05:14:16Z" level=debug msg="https://<my-ingress-name>/<path>" api=Query query=node_network_name_assign_type took=168.344446ms ts="2023-10-05 05:14:12.863 +0000 UTC"
10.244.0.13 - - [05/Oct/2023 05:14:16] "GET /api/v1/query HTTP/1.1 200 87" 0.168909 query=node_network_name_assign_type&time=1696482852.863

HTTP Call Log - 

time="2023-10-05T05:14:21Z" level=debug msg="https://<my-ingress-name>/<path>" api=LabelValues label=__name__ took=70.458394ms
time="2023-10-05T05:14:21Z" level=debug msg=LabelValues matchers="[]" name=__name__ took=70.685796ms

**Comment by tutaidalal** [comment]
Once i disable the auth from my ingress, its working now. Can's see how to pass the username password of my ingress as basic auth in server group config, can anyone please suggest the configuration

**Reply by tutaidalal** [reply, marked as answer]
```
        http_client:`
          basic_auth:
            username: 'username'
            password: 'password'
          tls_config:
            insecure_skip_verify: true
        ignore_error: true
        labels:
          promxy_cluster: my_cluster_name
        path_prefix: /my/prefix
        scheme: https
        static_configs:
        - targets:
                - ingress-host-name
```
