### DISCUSSION TITLE
Configuring HTTPS Prometheus servers

### DISCUSSION THREAD

**Discussion by szilardszabolcs** [jacksontj/promxy#712] [Q&A]
First of all, thank you for this very useful tool, it is one of simplest tools we are using for Prometheus high availability.

I had to move from HTTP to HTTPS Prometheus servers, but I couldn't figure out how to handle https Prometheus servers address in the promxy.yaml configuration.

```
##
### Promxy configuration
##
promxy:
  server_groups:
    - static_configs:
        - targets:
          - HOST1_IP:9090
          - HOST2_IP:9090
          - HOST3_IP:9090
          - HOST4_IP:9090
      scheme: http
      # options for promxy's HTTP client when talking to hosts in server_groups
      http_client:
        # dial_timeout controls how long promxy will wait for a connection to the downstream
        # the default is 200ms.
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
```
Can anyone please get me a working sample Promxy config with HTTPS Prometheus  nodes, if its possible?
Whoever helps me solve it, I'll plant a tree in my garden in his/her name!
