### ISSUE TITLE
Connection leak when using remote_read

### ISSUE THREAD

**Issue by yashumitsu** [jacksontj/promxy#109]
Thank you very much for your useful tool!

With an enabled option "remote_read", each request via Promxy leaves an unused ESTABLISHED connection to Prometheus backend.
Numbers of the connections is increasing and when it reaches approximatlly 500 simultaneous connections, service freezes. Keepalive closes these connections after 5 minutes, but it doesn't help much.

How to check, _config.yaml_:
```
global:
  evaluation_interval: 10s

promxy:
  server_groups:
    - static_configs:
      - targets:
        - prometheus:9090
      remote_read: true
      anti_affinity: 10s
      http_client:
        dial_timeout: 200ms
        tls_config:
          insecure_skip_verify: true
```

run:
`promxy --config=config.yaml --log-level=debug`

watch lsof on every query:
``lsof -r 2 -p `pidof promxy` ``

for example:
`curl 'http://localhost:8082/api/v1/query_range?query=up%7B%7D&start=1545912434.588&end=1545912734.588&step=1&_=1545912714581'`

Tested on v0.0.30 (with recent patch) and current master.
