### ISSUE TITLE
Getting changing data, with 2 nodes in Server Group

### ISSUE THREAD

**Issue by ghowland** [jacksontj/promxy#118]
I look at the data directly between the 2 servers, and they seem to basically match, but in Grafana through Promxy, the data jumps randowly, sometimes into invalid ranges (free memory goes negative).

Normal data:

![screen shot 2019-01-23 at 1 34 29 pm](https://user-images.githubusercontent.com/2231935/51639606-31fe4600-1f16-11e9-843b-d4f2f5edd380.png)

Deviation 1:

![screen shot 2019-01-23 at 1 36 35 pm](https://user-images.githubusercontent.com/2231935/51639613-37f42700-1f16-11e9-94ce-18be9f73f184.png)

Deviation 2:

![screen shot 2019-01-23 at 1 35 14 pm](https://user-images.githubusercontent.com/2231935/51639627-43475280-1f16-11e9-9b9f-b24092046fbb.png)

Config:

```
promxy:
  server_groups:
    - static_configs:
        - targets:
          - prometheus-infra-1.XXXXX.net:9090
          - prometheus-infra-2.XXXXX.net:9090
      # labels to be added to metrics retrieved from this server_group
      labels:
        sg: _prometheus_infra_ops_mode_net9090
      # anti-affinity for merging values in timeseries between hosts in the server_group
      anti_affinity: 10s
      # options for promxy's HTTP client when talking to hosts in server_groups
      http_client:
        # dial_timeout controls how long promxy will wait for a connection to the downstream
        # the default is 200ms.
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
```

Direct prom data 1:

![screen shot 2019-01-23 at 1 56 37 pm](https://user-images.githubusercontent.com/2231935/51639817-bc46aa00-1f16-11e9-8e32-bf2ab95c93f8.png)

Direct prom data 2:

![screen shot 2019-01-23 at 1 56 42 pm](https://user-images.githubusercontent.com/2231935/51639820-bea90400-1f16-11e9-91cc-a189e3418e62.png)

Ideas on why it would change like this?  Also I dont see where `anti_affinity` is documented, so I dont know if it's worth changing that.
