### ISSUE TITLE
relabel_configs should be metric_relabel_configs

### ISSUE THREAD

**Issue by Wing924** [jacksontj/promxy#136]
Hello!

https://github.com/jacksontj/promxy/blob/master/servergroup/config.go#L50-L55
```go
// RelabelConfigs are similar in function and identical in configuration as prometheus'
// relabel config for scrape jobs. The difference here being that the source labels
// you can pull from are from the downstream servergroup target and the labels you are
// relabeling are that of the timeseries being returned. This allows you to mutate the
// labelsets returned by that target at runtime.
RelabelConfigs []*config.RelabelConfig `yaml:"relabel_configs,omitempty"`
```
Please correct me if I'm wrong. According to this comment, it seems that `relabel_configs` apply not to each discovered target but to each sample.

Prometheus use `relabel_configs` to relabel discovered target and use `metric_relabel_configs` to relabel samples.

In addition, we need to relabel discovered target or we can't use many service discovery  methods other than `static_sd` and `file_sd`.

**Comment by jacksontj** [comment]
you are correct that the `relabel_configs` apply to the discovered target, but in the case of promxy the discovered targets are downstream prometheus hosts. This means you could (as an example, you probably wouldn't want to do this exactly...) add a label `prom_node="$hostname"` where `$hostname` would be the actual prometheus host name. This is helpful in cases where you have a sharded prometheus setup where a label you might add a label `prom_shard_number` or something similar.

**Comment by jacksontj** [comment]
@Wing924 did that clear it up? This can definitely be a bit complicated, so I want to make sure (1) we've cleared it up and (2) if we have, I'd like to update the docs to make it more clear (which I might need some suggestions on ;) )

**Comment by Wing924** [comment]
@jacksontj Sorry for late response. I understand why you want to name it not `metric_relabel_configs` but `relabel_configs`.  
But we need both prometheus' `metric_relabel_configs` and `relabel_configs` to make consul_sd and k8s_sd work as they need  prometheus' `metric_configs`.

**Comment by jacksontj** [comment]
So this `relabel_configs` is a promxy-side configuration, so this doesn't change the values of these for prometheus hosts (meaning whatever relabeling you do there is still done).

In addition, if you have been using relabel_configs to target only *some* hosts in a sd config (by using the `keep` action), this behavior still works (no change-- just trying to clarify the behavior in comments). The only difference is that you can now also use those to add labels to the series you query.


If that doesn't clear it up, maybe a more concrete example would help?

**Comment by Wing924** [comment]
This is what I want to do:
```yaml
promxy:
  server_groups:
  - consul_sd_configs:
    - services:
      - prometheus
    relabel_configs:
    - source_labels: [__meta_consul_metadata_group]
      regex: group1
      action: keep
  - consul_sd_configs:
    - services:
      - prometheus
    relabel_configs:
    - source_labels: [__meta_consul_metadata_group]
      regex: group2
      action: keep
```
but it looks don't work.

**Comment by jacksontj** [comment]
So, assuming the `group1` is a service meta on the target (prometheus); This would have worked before, and will continue to work. In prod this is (effectively) what I do for targeting (mine is through tags, but its effectively the same) :)

**Comment by Wing924** [comment]
Im a little confusing now. The promxy’s relabel_configs apply to both sd result and sample labels? We can use it to filter correct targets and drop labels like $hostname?
If so, could give me a example?

**Comment by jacksontj** [comment]
I'll give it a shot :)

To start off, lets look at an example prometheus scrape config with relabel

```
  relabel_configs:
  - source_labels: [__meta_consul_tags]
    regex: '.*,prod,.*'
    action: keep
  - source_labels: [__meta_consul_dc]
    regex: '.+'
    action: replace
    target_label: datacenter
```

If we saw this in a scrape-config we would expect (1) the scrape would only target hosts with a `prod` consul label and (2) it would add a label to all returned series of `datacenter` with the value set to whatever the value of `__meat_consul_dc` was.

If we saw this same config in promxy (pointing at prometheus hosts instead of some exporter), we'd expect a similar behavior: (1) only targets with the `prod` consul label would be included in the servergroup and (2) it would add a label to all returned series of this servergroup of `datacenter` with the value set to whatever the value of `__meat_consul_dc` was.

So in reality its "the same", the difference is in prometheus these apply to the labels/targets of a scrape job, in promxy they apply to the prometheus hosts in the servergroup - but the behavior is the same.


Hopefully that clears it up?
