### ISSUE TITLE
bad_data when querying VictoriaMetrics

### ISSUE THREAD

**Issue by jtyr** [jacksontj/promxy#183]
I'm trying to run Promxy in front of VictoriaMetrics (VM) which is fed by Telegraf. This is my Promxy config:

```yaml
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy
rule_files:
  - "*rule"
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - localhost:9093
remote_write:
  - url: http://localhost:8428/api/v1/write
promxy:
  server_groups:
    - static_configs:
        - targets:
          - localhost:8428
```

When I query VM, I get data:

```
$ curl 'http://localhost:8428/api/v1/query_range?query=system.n_cpus&time=1561377148.484&_=1561377121377'
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"system.n_cpus","db":"telegraf","host":"8d8530db2acf"},"values":[[1561377254,"4"],[1561377554,"4"]]}]}}
```
But when I query VM via Promxy, I get an error:

```
$ curl 'http://localhost:8082/api/v1/query_range?query=system.n_cpus&time=1561377148.484&_=1561377121377'
{"status":"error","errorType":"bad_data","error":"invalid parameter 'start': cannot parse \"\" to a valid timestamp"}
```

Any idea what could be wrong?

Another problem I have noticed with this setup is that if I query labels, Promxy crashes:

```
curl 'localhost:8082/api/v1/labels'
# Logs:
promxy_1           | panic: assignment to entry in nil map
promxy_1           | 
promxy_1           | goroutine 287 [running]:
promxy_1           | github.com/jacksontj/promxy/pkg/promclient.(*MultiAPI).LabelNames(0xc0001420f0, 0x27f7bc0, 0xc000123040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
promxy_1           | 	/go/src/github.com/jacksontj/promxy/pkg/promclient/multi_api.go:243 +0x636
promxy_1           | github.com/jacksontj/promxy/pkg/servergroup.(*ServerGroup).LabelNames(0xc00018a2a0, 0x27f7bc0, 0xc000123040, 0xc0000f6001, 0xc0007707a0, 0x1a770e1, 0xc00022a600, 0xc000770780, 0xc000770710, 0x1, ...)
promxy_1           | 	/go/src/github.com/jacksontj/promxy/pkg/servergroup/servergroup.go:290 +0x96
promxy_1           | github.com/jacksontj/promxy/pkg/promclient.(*MultiAPI).LabelNames.func1(0x27f7bc0, 0xc000123040, 0xc000174460, 0x0, 0xc000560540, 0x280c100, 0xc00018a2a0)
promxy_1           | 	/go/src/github.com/jacksontj/promxy/pkg/promclient/multi_api.go:205 +0x8e
promxy_1           | created by github.com/jacksontj/promxy/pkg/promclient.(*MultiAPI).LabelNames
promxy_1           | 	/go/src/github.com/jacksontj/promxy/pkg/promclient/multi_api.go:203 +0x2a9
```

VM returns labels just fine:

```
$ curl 'localhost:8428/api/v1/labels'
{"status":"success","data":["__name__","cpu","db","device","fstype","host","mode","name","path"]}
```
