### ISSUE TITLE
Slow query response times

### ISSUE THREAD

**Issue by geekhead** [jacksontj/promxy#188]
### Issue 
A simple query using the `up{}` metric for the last 7 days or even just the last 3-4 results in a 3-5 second delay. The same query going directly to either of the VictoriaMetrics backends results in only a 130-170ms delay. I understand that Promxy has to query all the servers in the server group and then merge the results but a ~180% increase in query times seems a little much for my simple setup.  

### Setup
So I have a very simple setup of two instances. Each instance is running VictoriaMetrics (version 1.20.7) and Prometheus (2.9.2). I have one of those instances running Promxy (v0.0.41) with the two VictoriaMetrics instances in a server group. 

Promxy config:
```
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy

promxy:
  server_groups:
    - static_configs:
      - targets:
        - prometheus1-a:8428
        - prometheus1-b:8428
      labels:
        sg: VM_Cluster1
      anti_affinity: 10s
      remiote_read: false
      http_client:
        diial_timeout: 2s
        tls_config:
          insecure_skip_verify: true
```

### Results
Going directly to a VictoriaMetric instance
![Screen Shot 2019-07-02 at 11 56 28 AM](https://user-images.githubusercontent.com/2513533/60528496-8c1fe600-9cc2-11e9-868c-1a067df9ef95.png)

![Screen Shot 2019-07-02 at 11 56 38 AM](https://user-images.githubusercontent.com/2513533/60528495-8c1fe600-9cc2-11e9-9a0b-0f37b9696641.png)

Going directly to Promxy
![Screen Shot 2019-07-02 at 11 54 47 AM](https://user-images.githubusercontent.com/2513533/60528683-f6d12180-9cc2-11e9-9d5a-66738375b7e0.png)

![Screen Shot 2019-07-02 at 11 55 01 AM](https://user-images.githubusercontent.com/2513533/60528682-f6d12180-9cc2-11e9-977b-d3e7ba419c2d.png)

Here's the actual Promxy log line entries when doing the following queries:
**Last 2 days:** `[02/Jul/2019 16:22:00] "GET /api/v1/query_range HTTP/1.1 200 6945" 1.794222 start=1561911720&end=1562084520&step=120&query=up%7B%7D`
**Last 7 days:**`[02/Jul/2019 16:23:07] "GET /api/v1/query_range HTTP/1.1 200 5163" 3.456831 start=1561479600&end=1562084400&step=300&query=up%7B%7D`

Let me know if you need any other additional info. Thanks
