### ISSUE TITLE
422 Unprocessable Entity error due to too large default "end" time

### ISSUE THREAD

**Issue by skirino** [jacksontj/promxy#193]
Hi!

We are running multiple prometheus servers for high availability in our Kubernetes cluster.
Traffic between grafana and prometheus servers are properly routed thanks to promxy.

However, when we use [k8s-prometheus-adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter) so that [horizontal pod autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) utilizes metrics stored in our prometheus servers for judging whether to scale, unfortunately promxy doesn't correctly respond to k8s-prometheus-adapter.
(Currently we work-around this by directly connecting k8s-prometheus-adapter with 1 specific prometheus server; the HPA is working fine.)

From the logs k8s-prometheus-adapter sends the following request to promxy:
```
GET /api/v1/series?match%5B%5D=%7B__name__%3D~%22%5Econtainer_.%2A%22%2Ccontainer_name%21%3D%22POD%22%2Cnamespace%21%3D%22%22%2Cpod_name%21%3D%22%22%7D&start=1561358209.849
```

And promxy returns 422 error for this, due to very large (far future) timestamp "292277025-08-18T16:12:54.999+09:00" is rejected by prometheus.

---

This issue can be reproduced as follows:

1. Create a `prometheus.yml`. Any valid config should be OK; as an example:

    ```
    global:
      scrape_interval: 15s
      external_labels:
        monitor: 'codelab-monitor'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
    ```

2. `$ prometheus --log-level=debug`
3. Create `config.yaml` that points to the running prometheus:

    ```
    promxy:
      server_groups:
      - anti_affinity: 10s
        labels: {}
        static_configs:
        - targets:
          - localhost:9090
    ```

4. `$ promxy --log-level=trace`
5. Send request:

    ```
    $ curl 'http://localhost:8082/api/v1/series?match%5B%5D=%7B__name__%3D~%22%5Econtainer_.%2A%22%2Ccontainer_name%21%3D%22POD%22%2Cnamespace%21%3D%22%22%2Cpod_name%21%3D%22%22%7D&start=1561358209.849'
    {"status":"error","errorType":"execution","error":"bad_data: cannot parse \"292277025-08-18T16:12:54.999+09:00\" to a valid timestamp"}
    ```

The expected response is obtained by directly sending to prometheus:

```
$ curl 'http://localhost:9090/api/v1/series?match%5B%5D=%7B__name__%3D~%22%5Econtainer_.%2A%22%2Ccontainer_name%21%3D%22POD%22%2Cnamespace%21%3D%22%22%2Cpod_name%21%3D%22%22%7D&start=1561358209.849' 
{"status":"success","data":[]}
```

Versions:
- prometheus: 2.10.0
- promxy: 0.0.42

---

Note:
After some investigation, I realized that, since original request doesn't contain `end` query parameter,
`end` timestamp is filled with a [very large value](https://github.com/jacksontj/promxy/blob/master/vendor/github.com/prometheus/prometheus/web/api/v1/api.go#L443) by [prometheus/web/api/v1/api](https://github.com/jacksontj/promxy/blob/master/vendor/github.com/prometheus/prometheus/web/api/v1/api.go#L473).
Prometheus server rejects this very large `end` timestamp sent from promxy, resulting in 422 error on promxy.
