### ISSUE TITLE
K8S promxy kubernetes_sd_configs doesn't work.

### ISSUE THREAD

**Issue by wizard580** [jacksontj/promxy#198]
I can't make k8s prometheus instances autodiscovery work.
That's the part of my config.yaml
```
    promxy:
      server_groups:
      - kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: prometheus
          action: keep
        - source_labels: [__meta_kubernetes_namespace]
          regex: monitoring
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex: 9090
          action: keep
```
My prometheus instances are StatefulSet, replicas=2

They have only one label: `app=prometheus`
```
kubectl -n monitoring get pod -l app=prometheus
NAME           READY     STATUS    RESTARTS   AGE
prometheus-0   1/1       Running   0          3d
prometheus-1   1/1       Running   0          3d
```
They are reachable and promxy works fine (if I'll use static config).
Can you point me to the place I did mistake?

Thanks!
