### ISSUE TITLE
Data loss when merging from two VictoriaMetrics servers

### ISSUE THREAD

**Issue by fatgit** [jacksontj/promxy#203]
I've setup Promxy over two VictoriaMetrics servers and Grafana looks at promxy.

I stopped VictoriaMetrics#1 server. Everything looks good, Grafana draws a full graph.

I started VictoriaMetrics#1 server again and result of the merge:

Data from VictoriaMetrics#1
<img width="1428" alt="vic-1" src="https://user-images.githubusercontent.com/11026137/62152147-ce831580-b2b6-11e9-8e96-aef63c021e61.png">

Data from VictoriaMetrics#2
<img width="1542" alt="vic-2" src="https://user-images.githubusercontent.com/11026137/62152165-d6db5080-b2b6-11e9-9d4e-013179af2f30.png">

Data from Promxy
<img width="1532" alt="proxmy" src="https://user-images.githubusercontent.com/11026137/62152102-ae535680-b2b6-11e9-9241-867a91cff610.png">

How to make that the result of the merge would be like from VictoriaMetrics#2 instead VictoriaMetrics#1?

My config:

 ```
promxy:
  server_groups:
    - static_configs:
        - targets:
          - vic-1:8428
          - vic-2:8428
      anti_affinity: 2s
      remote_read: false
      path_prefix: /
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
```
