### ISSUE TITLE
HA does not seem to be working

### ISSUE THREAD

**Issue by raags** [jacksontj/promxy#214]
I have set up Grafana with Promxy and Prometheus HA pair like so :

```
Grafana -> LB |--> Promxy1 |--> Prometheus1
              |--> Promxy2 |--> Prometheus2
```
To test HA, I shutdown Promethues1, and expected Promxy to server data from Promethues2 instance. However, Grafana throws the below exception:

![Screenshot 2019-09-03 at 1 44 41 PM](https://user-images.githubusercontent.com/697714/64156272-136c1000-ce52-11e9-974e-161e20327dad.png)

Configuration is:
```
promxy:
  server_groups:
    # All upstream prometheus service discovery mechanisms are supported with the same
    # markup, all defined in https://github.com/prometheus/prometheus/blob/master/discovery/config/config.go#L33
    - static_configs:
        - targets:
            - 172.31.49.191:9090
            - 172.31.67.21:9090
      # labels to be added to metrics retrieved from this server_group
      labels:
        sg: prometheus
      http_client:
        # dial_timeout controls how long promxy will wait for a connection to the downstream
        # the default is 200ms.
        dial_timeout: 1s
```

Some graphs seem to work though. Seems to be related to templating.
