### ISSUE TITLE
Comparing to remote_read

### ISSUE THREAD

**Issue by Wing924** [jacksontj/promxy#22]
Hello!
Currently, I use prometheus remote_read to archive:

* no more "holes" in metrics
* single source in grafana
* no need for aggregation layers of prometheus anymore!

*I konw this function is not designed for this purpose, but it works.*

My config is like:
```yml
remote_read:
- url: http://prom-us1:9090/api/v1/read
- url: http://prom-us2:9090/api/v1/read
- url: http://prom-jp1:9090/api/v1/read
- url: http://prom-jp2:9090/api/v1/read
```
I found remote_read  is faster than promxy with some queries.
For example, simple query like `cpu_usage{hostname="myserver"}`, remote_read is fater than promxy. But aggregated query like `count(up{})`,  promxy is fater than remote_read.

I think it's needed to add a document to compare and benchmark remote_read and promxy.
