### ISSUE TITLE
consul_sd_discovery ignores config?

### ISSUE THREAD

**Issue by Samgarr** [jacksontj/promxy#229]
Hello,
i'm trying to use promxy with consul discovery like this:
```
promxy:
  server_groups:
    - consul_sd_configs:
      - server: localhost:8585
      - services:
        - vmetrics_dev
      datacenter: dc1
```
After starting promxy, debug logs shows weird things:
```
{"caller":"consul.go:268","discovery":"consul","err":"Get http://localhost:8500/v1/agent/self: dial tcp 127.0.0.1:8500: connect: connection refused","level":"error","msg":"Error retrieving datacenter name","ts":"2019-10-23T14:47:42.125Z"}
DEBU[2019-10-23T16:47:47+02:00] Updating targets from discovery manager      
DEBU[2019-10-23T16:47:47+02:00] Updating targets from discovery manager:
[*** 
*** all nodes from consul, not even "vmetrics_dev" which i have configured in config
***] 
INFO[2019-10-23T16:47:47+02:00] promxy starting
```
Looks like promxy ignoring `services` setting and also querying localhost:8500 even if `server` is configured to localhost:8585. Or i'm having wrong config?
If you need mode logs or info let me know! Thank you.
