### ISSUE TITLE
Runtime panic using scalar(), again

### ISSUE THREAD

**Issue by perlun** [jacksontj/promxy#234]
Thanks for a nice tool. :+1: When testing it out, we have run into a bug which is seemingly similar to #219, but we are experiencing this with a recent version of promxy where that particular bug should be fixed.

## Description
Just like described late in #219, performing a `scalar()` query triggers an "invalid memory address or nil pointer dereference" error. Nothing gets logged to the systemd log, unfortunately.

This is an example of a query that triggers the problem. When querying Prometheus directly, the query works without issues and returns a `NaN` value.

```promql
scalar(up{instance="backend1:8083"}) * 1 +
scalar(up{instance="backend2:8083"}) * 2
```

## Versions
- Promxy v0.0.54
- Prometheus 2.13.1

## Config
```yaml
promxy:
  server_groups:
    # All upstream prometheus service discovery mechanisms are supported with the same
    # markup, all defined in https://github.com/prometheus/prometheus/blob/master/discovery/config/config.go#L33
    - static_configs:
      - targets:
        - prometheus-node1:9090
        - prometheus-node2:9090

      # anti-affinity for merging values in timeseries between hosts in the server_group
      anti_affinity: 10s

      # Controls whether to use remote_read or the prom HTTP API for fetching remote raw data
      remote_read: true
```
