### ISSUE TITLE
Promxy stop showing metrics if one prometheus is down

### ISSUE THREAD

**Issue by Dlorite** [jacksontj/promxy#240]
We have a promxy with this configuration.

```
 promxy:
      server_groups:
        - static_configs:
          - targets:
            - prometheus:9090
        - static_configs:
          - targets:
            - prometheus-2:9090
        - static_configs:
          - targets:
            - prometheus-3:9090
        - static_configs:
          - targets:
            - prometheus-4:9090
```

If one of these prometheus is down, promxy doesn't give us metrics.

Regards.
