### ISSUE TITLE
promxy and alertmanager

### ISSUE THREAD

**Issue by AeroNotix** [jacksontj/promxy#250]
Hi,

I'm wondering if promxy can solve my current dilemma. 

I have several separate prometheus instances, all remote writing into victoria metrics. VictoriaMetrics is set up as the single datasource in grafana. All is good!

Except I want to use AlertManager, I don't want to have to maintain separate rules/alerts files for each individual promtheus and I want all alerts to be forwarded to a single alerts manager cluster.

I came across this project - it looks interesting, and may indeed solve my problem. Am I correct in assuming that it can?

**Comment by jacksontj** [comment]
Yes, promxy can execute alerting/recording rules -- these will also be an aggregate result and send to whatever alertmanager you configure. So you can create global alerts and send to a single alertmanager cluster.

**Comment by AeroNotix** [comment]
Thank you. I have stood it up in our infra and am having some issues:

Running locally where I kubectl port-forward a victoria-metrics select endpoint to my local machine, and port-forward an alert-manager to my local machine - then run promxy with config which access both those local ports - rules evaluate and work fine.

When I deploy this, pointing at the same endpoints, but in kubernetes directly. Alert rules always stay at green/0 active - yet the metrics are queryable from the promxy UI. 

Any ideas what could be causing that?

**Comment by jacksontj** [comment]
It sounds like some sort of network issue, but I'm not sure. I'd suggest looking at debug logs (it should include the rule evals as well as the sends to alertmanager, etc.)

**Comment by AeroNotix** [comment]
I can add a WatchDog rule and it evaluates and sends off to alert manager just fine:

```yaml
alert: Watchdog
expr: vector(1)
labels:
  severity: none
annotations:
  message: |
    This is an alert meant to ensure that the entire alerting pipeline is functional.
    This alert is always firing, therefore it should always be firing in Alertmanager
    and always fire against a receiver. There are integrations with various notification
    mechanisms that send a notification when this alert is not firing. For example the
    "DeadMansSnitch" integration in PagerDuty.
```

Copied from prometheus-operator's built in WatchDog rule.

Running locally, things "Just Work" but running in kubernetes, things are different... the exact same config is running locally/kubernetes aside from the hostnames for alertmanager/victoria. 

It simply seems that the alert rule is never evaluating to "alerting". Any other ideas I could look at?

**Comment by AeroNotix** [comment]
Honestly @jacksontj this is quite strange and I'm not understanding why it works locally, but not in kubernetes. I can query through promxy's UI for the exact same metrics which never end up alerting. 

Here's some simple alert: 
![Mon__2_Dec_21:43:44_CET_2019](https://user-images.githubusercontent.com/975962/69994004-3ee3c100-154d-11ea-8518-feea7f4ff7fe.jpg)

Here's me querying it in the promxy UI: 
![Mon__2_Dec_21:44:13_CET_2019](https://user-images.githubusercontent.com/975962/69994045-502ccd80-154d-11ea-84df-6308237d7c17.jpg)

Here's it getting results: 
![Mon__2_Dec_21:44:41_CET_2019](https://user-images.githubusercontent.com/975962/69994065-5d49bc80-154d-11ea-9350-fc98eac28565.jpg)

Yet locally, it works?

What am I missing?

**Comment by AeroNotix** [comment]
Here's the config I am using:

```yaml
##
## Regular prometheus configuration
##
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
- "/app/rules/*rule.yaml"

# Alerting specifies settings related to the Alertmanager.
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - $ALERT_MANAGER_URL

# remote_write configuration is used by promxy as its local Appender, meaning all
# metrics promxy would "write" (not export) would be sent to this. Examples
# of this include: recording rules, metrics on alerting rules, etc.
remote_write:
  - url: http://127.0.0.1:8083/receive

##
### Promxy configuration
##
promxy:
  server_groups:
    # All upstream prometheus service discovery mechanisms are supported with the same
    # markup, all defined in https://github.com/prometheus/prometheus/blob/master/discovery/config/config.go#L33
    - static_configs:
        - targets:
          - $VICTORIA_METRICS_URL
      # Controls whether to use remote_read or the prom HTTP API for fetching remote raw data
      remote_read: true
      path_prefix: /select/2/prometheus/
      query_params:
        nocache: 1
      # options for promxy's HTTP client when talking to hosts in server_groups
      http_client:
        # dial_timeout controls how long promxy will wait for a connection to the downstream
        # the default is 200ms.
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
```
