### ISSUE TITLE
ServerGroups not being registered

### ISSUE THREAD

**Issue by Janesee3** [jacksontj/promxy#254]
Hi, I'm trying to get promxy to work with VictoriaMetrics. However, my promxy instance does not seem to be registering any ServerGroups, thus I'm getting no data points when I query Promxy from Grafana.

**My Setup**
- 2 Prometheus server pods, both are using remote_write to write to VictoriaMetrics
- VictoriaMetrics running in cluster mode, with 2 sets of components (vmselect-0, vm-select-1, vm-insert-0, vm-insert-1....etc)
- Promxy deployment with single replica. I have a single ServerGroup configured to point at my VictoriaMetrics Select component (this component was originally serving as the datasource for my Grafana dashboard)

Here's the full list of K8S manifests I had to deploy for Promxy:
```yaml
---
apiVersion: v1
data:
  config.yaml: |
    promxy:
      server_groups:
      - kubernetes_sd_configs:
        - role: pod
          namespace: 
            names:
              - vm
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            action: keep
            regex: 'vm-victoria-metrics-cluster-vmselect*'

kind: ConfigMap
metadata:
  name: promxy-config
  namespace: prom
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: promxy
  name: promxy
  namespace: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promxy
  template:
    metadata:
      labels:
        app: promxy
    spec:
      serviceAccountName: promxy
      containers:
      - args:
        - "--config=/etc/promxy/config.yaml"
        - "--web.enable-lifecycle"
        - "--log-level=trace"
        env:
          - name: ROLE
            value: "1"
        command:
        - "/bin/promxy"
        image: quay.io/jacksontj/promxy:latest
        imagePullPolicy: Always
        name: promxy
        ports:
        - containerPort: 8082
        volumeMounts:
        - mountPath: "/etc/promxy/"
          name: promxy-config
          readOnly: true
      volumes:
      - configMap:
          name: promxy-config
        name: promxy-config
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prom-admin
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints", "services"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prom-rbac
subjects:
- kind: ServiceAccount
  name: promxy
  namespace: prom
roleRef:
  kind: ClusterRole
  name: prom-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promxy
  namespace: prom
```

**The Issue**
When we link up Promxy as a datasource on Grafana, it passes the health check but it is not serving any datapoints.

When we portforward the Promxy pod and went to `/graph` to view the web UI, we see nothing under the `Targets` and `Service Discovery` tabs. When we execute queries, there was also nothing returned

**Others**
On a side note, what is the difference between using Promxy and Prometheus Federation? 

Thanks in advance!
