### ISSUE TITLE
remote_read not working

### ISSUE THREAD

**Issue by samsk** [jacksontj/promxy#262]
I believe remote_read is not working, and promxy always uses query API instead. I've tried version 0.0.56, 0.0.57 and also git head, with same results.

My config:
```
    - static_configs:
        - targets:
#            - 10.252.64.2:9090
            - 10.252.64.3:9090
      labels:
        mon_id: ''
      anti_affinity: 10s
      remote_read: true
```

in tcpdump i see
```
....
POST /api/v1/query HTTP/1.1
Host: 10.252.64.3:9090
User-Agent: Go-http-client/1.1
Content-Length: 47
Content-Type: application/x-www-form-urlencoded

query=up%7Bmon%3D%22x%22%7D&time=1581147336.745
```
