### ISSUE TITLE
Grafana instant queries don't work

### ISSUE THREAD

**Issue by beorn-** [jacksontj/promxy#264]
When i use enable the "instant" query type in a promql grafana query there's no result (of course with it disabled it's fine)

any idea ?

**Comment by jacksontj** [comment]
Thats curious, as that is a very common use-case for a lot of users. Do you have some configuration etc. to reproduce the problem? Or some other information to help debug?

**Comment by beorn-** [comment]
Simple configuration
```
promxy -> victoria-metrics (from now to the given datetime T)
       \- metrictank       (from T to ever)
```
with promxy config :
```
global:    
  evaluation_interval: 5s    
  external_labels:           
    source: promxy           
                      
rule_files: []        
                  
alerting:         
  alertmanagers: []    
                       
remote_write: []       
                                          
promxy:                
  server_groups:       
    - static_configs:        
      - targets:         
        - victoriametrics01:8428    
        - victoriametrics02:8428    
      anti_affinity: 10s                                                  
      remote_read: False            
      remote_read_path: ''          
      path_prefix: ''               
      http_client:                                            
        dial_timeout: 5s            
      absolute_time_range:          
        start: '2020-02-07T15:13:00Z'    
                                         
    - static_configs:                    
      - targets:                                                               
        - metrictank01:6060                                            
        - metrictank02:6060              
        - metrictank03:6060              
        - metrictank04:6060              
      anti_affinity: 10s                 
      remote_read: False                 
      remote_read_path: '/prometheus'    
      path_prefix: '/prometheus'         
      http_client:                       
        dial_timeout: 5s                 
      absolute_time_range:               
        end: '2020-02-07T15:13:00Z'
```
Fyi the very same instant query shows up just fine if queried directly through victoria metrics or metrictank

**Comment by beorn-** [comment]
i'll try to get the api query/result with a simple MITM on the api if you like

**Comment by jacksontj** [comment]
If you could that would help. If you'd prefer to not get a pcap you can just include the trace log output (which should include that information).

**Comment by beorn-** [comment]
`Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=debug msg="AggregateExpr sum(kafka_brokers{job=~\"kriek\"}) sum"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=debug msg="http://metrictank06:6060/prometheus" api=Query query="sum(kafka_brokers{job=~\"kriek\"})" ts="2020-02-19 16:04:04 +0100 CET"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=debug msg="http://metrictank08:6060/prometheus" api=Query query="sum(kafka_brokers{job=~\"kriek\"})" ts="2020-02-19 16:04:04 +0100 CET"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=debug msg="http://victoriametrics02:8428" api=Query query="sum(kafka_brokers{job=~\"kriek\"})" ts="2020-02-19 16:04:04 +0100 CET"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=debug msg="http://metrictank07:6060/prometheus" api=Query query="sum(kafka_brokers{job=~\"kriek\"})" ts="2020-02-19 16:04:04 +0100 CET"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=debug msg="http://metrictank05:6060/prometheus" api=Query query="sum(kafka_brokers{job=~\"kriek\"})" ts="2020-02-19 16:04:04 +0100 CET"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=trace msg="http://metrictank07:6060/prometheus" api=Query error="<nil>" query="sum(kafka_brokers{job=~\"kriek\"})" took="55.25µs" ts="2020-02-19 16:04:04 +0100 CET" value="<nil>" warnings="[]"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=trace msg="http://metrictank06:6060/prometheus" api=Query error="<nil>" query="sum(kafka_brokers{job=~\"kriek\"})" took="79.677µs" ts="2020-02-19 16:04:04 +0100 CET" value="<nil>" warnings="[]"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=trace msg="http://metrictank05:6060/prometheus" api=Query error="<nil>" query="sum(kafka_brokers{job=~\"kriek\"})" took="65.642µs" ts="2020-02-19 16:04:04 +0100 CET" value="<nil>" warnings="[]"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=trace msg="http://metrictank08:6060/prometheus" api=Query error="<nil>" query="sum(kafka_brokers{job=~\"kriek\"})" took="75.905µs" ts="2020-02-19 16:04:04 +0100 CET" value="<nil>" warnings="[]"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=debug msg="http://victoriametrics01:8428" api=Query query="sum(kafka_brokers{job=~\"kriek\"})" ts="2020-02-19 16:04:04 +0100 CET"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=trace msg="http://victoriametrics01:8428" api=Query error="<nil>" query="sum(kafka_brokers{job=~\"kriek\"})" took=3.202141ms ts="2020-02-19 16:04:04 +0100 CET" value="{} => 8 @[1582124613]" warnings="[]"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=trace msg="http://victoriametrics02:8428" api=Query error="<nil>" query="sum(kafka_brokers{job=~\"kriek\"})" took=4.417843ms ts="2020-02-19 16:04:04 +0100 CET" value="{} => 8 @[1582124613]" warnings="[]"
Feb 19 16:04:03 victoriametrics01 promxy[21538]: 10.10.0.51 - - [19/Feb/2020 15:04:03] "GET /api/v1/query HTTP/1.1 200 87" 0.007499 query=sum%28kafka_brokers%7Bjob%3D~%22kriek%22%7D%29&time=1582124644
`

**Comment by jacksontj** [comment]
From this log output it seems that the downstream is returning data:

```
victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=trace msg="http://victoriametrics02:8428" api=Query error="<nil>" query="sum(kafka_brokers{job=~\"kriek\"})" took=4.417843ms ts="2020-02-19 16:04:04 +0100 CET" value="{} => 8 @[1582124613]" warnings="[]" Feb 19 16:04:03
```

In that the return value was 8 for the query `sum(kafka_brokers{job=~"kriek"})` similar value for victoriametrics01:

```
16:04:03 victoriametrics01 promxy[21538]: time="2020-02-19T16:04:03+01:00" level=trace msg="http://victoriametrics01:8428" api=Query error="<nil>" query="sum(kafka_brokers{job=~\"kriek\"})" took=3.202141ms ts="2020-02-19 16:04:04 +0100 CET" value="{} => 8 @[1582124613]" warnings="[]" Feb 19 16:04:03
```

(also 8) -- so I'd expect it to work, but I'm assuming it didn't? If it didn't could you try adding a `labels` section to both servergroups (anything as long as they don't match) and see if that resolves it? If so its actually related to https://github.com/jacksontj/promxy/issues/260#issuecomment-587975870 -- but if that were the case I'd expect it to have problems for query and query_range.

**Comment by beorn-** [comment]
i did not expect it to agregate over multiple promethei. according to the configuration. for such queries it should only query victoriametrics backends don't you think ?

**Comment by jacksontj** [comment]
The way the timefilter client works (https://github.com/jacksontj/promxy/blob/master/pkg/promclient/timefilter.go#L21) it simply returns nil if you are outside the time range it wants. So in the trace you have it does seem to be working properly (nil for the metrictank, and 8 for the VM hosts). So I'm at a loss for why this would not return data (since it definitely has some data in there). The only thing I can think of is this label issue since they are returning nil -- maybe its picking that (should be easy to confirm by adding labels to the 2 SGs).

**Comment by beorn-** [comment]
tried to add sg to both servers no luck

**Comment by beorn-** [comment]
Oh. I'm so sorry. I mixed up start and end.

The start/end. These are right if you look from now to the past not the other way around. Honest mistake !

**Comment by jacksontj** [comment]
So it sounds like the issue is gone now?

**Comment by beorn-** [comment]
just testing again. to be 100% sure.

**Comment by beorn-** [comment]
Well. No. my configuration was right. sorry. it's still there.

**Comment by beorn-** [comment]
after using a current build still no lock. but after i change my configuration to this, instant queries came back ok :

```
global:    
  evaluation_interval: 5s    
  external_labels:           
    source: promxy           
                      
rule_files: []        
                  
alerting:         
  alertmanagers: []    
                       
remote_write: []       
                                          
promxy:                
  server_groups:       
    - static_configs:        
      - targets:         
        - victoriametrics01:8428    
        - victoriametrics02:8428    
      anti_affinity: 10s                                                  
      remote_read: False            
      remote_read_path: ''          
      path_prefix: ''
      query_params:
        nocache: 1
      http_client:                                            
        dial_timeout: 5s            
    - static_configs:                    
      - targets:                                                               
        - metrictank01:6060                                            
        - metrictank02:6060              
        - metrictank03:6060              
        - metrictank04:6060              
      anti_affinity: 10s                 
      remote_read: False                 
      remote_read_path: '/prometheus'    
      path_prefix: '/prometheus'         
      http_client:                       
        dial_timeout: 5s                 
      absolute_time_range:               
        end: '2020-02-07T15:13:00Z'

```

then it worked : disabled cache on the victoria metrics backend and also removed the absolute timerange. then it worked fine
