### ISSUE TITLE
Metric names not preserved in query

### ISSUE THREAD

**Issue by carlossicilia** [jacksontj/promxy#274]
Hello! I'm running into an issue where it seems that the metric name is not being preserved, and it leads to duplication errors.

Setup:

- Two identically configured v2.15.2 prometheus servers for HA running in k8s installed by the community helm chart promtheus-operator

- One v0.0.57 promxy running in a pod with the following configuration:

```
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s
      external_labels:
        source: promxy
    remote_write:
    promxy:
      server_groups:
        - static_configs:
            - targets:
              - prom-server-0
              - prom-server-1
          labels:
            server_group: group_1
          anti_affinity: 30s
          remote_read: true
          remote_read_path: api/v1/read
          path_prefix:
          query_params:
            nocache: 1
          http_client:
            dial_timeout: 10s
            tls_config:
              insecure_skip_verify: false
          relative_time_range:
            start:
            end:
          absolute_time_range:
            start:
            end:
          ignore_error: true
```
Query Specifics:
We have 4 metrics with different values:

- metric_1 
- metric_10
- metric_1000
- metric_10000

This query returns an error:

```
avg ({__name__=~"metric_.*"}) by (__name__)

Error executing query: found duplicate series for the match group {__name__="metric_10"} on the right hand-side of the operation: [{__name__="metric_10"}, {__name__="metric_1"}];many-to-many matching not allowed: matching labels must be unique on one side
```

On our prometheus servers however, the metric names are preserved and yield 4 different time series such as:

- metric_1{} = 1
- metric_10{} = 10
- metric_1000{} = 1000
- metric_10000{} = 10000

here are some logs from that query:

```
time="2020-02-26T19:58:08Z" level=debug msg="AggregateExpr avg by(__name__) ({__name__=~\"metric_.*\"}) avg"
time="2020-02-26T19:58:08Z" level=debug msg="AggregateExpr count by(__name__) ({__name__=~\"metric_.*\"}) count"
time="2020-02-26T19:58:08Z" level=debug msg="http://prom-server-1" api=Query query="count by(__name__) ({__name__=~\"metric_.*\"})" ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:08Z" level=debug msg="AggregateExpr sum by(__name__) ({__name__=~\"metric_.*\"}) sum"
time="2020-02-26T19:58:08Z" level=debug msg="http://prom-server-0" api=Query query="count by(__name__) ({__name__=~\"metric_.*\"})" ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:08Z" level=debug msg="http://prom-server-1" api=Query query="sum by(__name__) ({__name__=~\"metric_.*\"})" ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:08Z" level=debug msg="http://prom-server-0" api=Query query="sum by(__name__) ({__name__=~\"metric_.*\"})" ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:09Z" level=debug msg="http://prom-server-0" api=Query query="sum by(__name__) ({__name__=~\"metric_.*\"})" took=92.94947ms ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:09Z" level=debug msg="http://prom-server-0" api=Query query="count by(__name__) ({__name__=~\"metric_.*\"})" took=95.979287ms ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:09Z" level=debug msg="http://prom-server-1" api=Query query="count by(__name__) ({__name__=~\"metric_.*\"})" took=104.073632ms ts="2020-02-26 19:58:08.818 +0000 UTC"
time="2020-02-26T19:58:09Z" level=debug msg="http://prom-server-1" api=Query query="sum by(__name__) ({__name__=~\"metric_.*\"})" took=105.678827ms ts="2020-02-26 19:58:08.818 +0000 UTC"
100.97.247.189 - - [26/Feb/2020 19:58:09] "GET /api/v1/query HTTP/1.1 422 233" 0.107625 query=avg+%28%7B__name__%3D~%22metric_.%2A%22%7D%29+by+%28__name__%29&time=1582747088.818&_=1582739994726
```

I also tested this setup with v2.13.0 of prometheus, but got the same error. Please let me know if you need more information.
