### ISSUE TITLE
Promxy config file to connect with Thanos Querier

### ISSUE THREAD

**Issue by vishnubraj** [jacksontj/promxy#302]
Hi, I want to connect Thanos Querier using promxy, Can you please provide a sample config file.
I couldn't find any doc on the internet.

The below mentioned is the config file I am using now and it's not working.

```
promxy:
  server_groups:
    - static_configs:
        - targets:
          - localhost:8428                #victoriametrics 
          - 192.168.102.200:19190. #thanos   
      anti_affinity: 10s
      remote_read: true
      remote_read_path: api/v1/read
      query_params:
        nocache: 1
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
```
