### ISSUE TITLE
Promxy not showing data

### ISSUE THREAD

**Issue by vishnubraj** [jacksontj/promxy#303]
I have Thanos and victorymetrics both.
on victoriametrics I have data till 20th April and Thanos has the latest data.
I am using promxy to connect to both. when I query for the last 2 days I see the Thanos metrics and when I query for the last 30 days I only see the victorimetrics and I don't see the Thanos metrics. Can you please help me with this.

Below is my promxy config
```
promxy:
  server_groups:
    - static_configs:
        - targets:
          - localhost:8428
          - 192.168.102.200:19190
      labels:
        instance: opstest1.sjc2:9100
      query_params:
        nocache: 1
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
```
