### ISSUE TITLE
ServerGroup config

### ISSUE THREAD

**Issue by ritessh** [jacksontj/promxy#306]
Can I have sample config.yaml with 2 Prometheus node?  I tried to add 2 static configs in config yaml, but when first static config  node is down, promxy is not able to fetch data.

**Comment by jacksontj** [comment]
If the 2 prometheus nodes have unique data then they'll need to be in separate ServerGroups with different `labels` associated with each. So something like:

```
promxy:
  server_groups:
    - static_configs:
        - targets:
          - localhost:9090
      labels:
        sg: localhost_9090
    - static_configs:
        - targets:
          - localhost:9091
      labels:
        sg: localhost_9091
```

Should be sufficient
