### ISSUE TITLE
Deadlock/hang when configuring >1 consul_sd server_groups with tags

### ISSUE THREAD

**Issue by frebib** [jacksontj/promxy#313]
This is a strange one, it took me a while to pin down exactly what was going on. At first I thought the server was messing me around. It appears that whilst trying to enumerate the server_groups at first startup, promxy locks up and never resumes. Happens both with 0.0.58 and 0.0.59. Running on Linux x86_64. I haven't tried any other builds
Here is some config to reproduce the hang:
```
global:
  evaluation_interval: 60s
  scrape_interval: 60s
  scrape_timeout: 20s
promxy:
  server_groups:
  - consul_sd_configs:
    - server: localhost:8500
      datacenter: sfo07
      services:
      - prometheus-rack
      tags:
      - sw00.sfo07
  - consul_sd_configs:
    - server: localhost:8500
      datacenter: sfo07
      services:
      - prometheus-rack
      tags:
      - sw01.sfo07
```
Removing the tags from either allows promxy to start, but as soon as both have a list of tags it hangs.
Some logs, but they're not particularly useful: https://gist.github.com/frebib/00fd781a1ca921f00b49edb363252c51

Our use case is two Prometheis per rack in a server_group, with n racks, all aggregated by promxy. It's orchestrated by nomad, hence the use of consul. It's pretty early testing at the moment, so hopefully we can get this working. Cardinality and WAL size is starting to get crazy.
I'm happy to debug given that we already have the environment set up, but I'll need some pointers on where to look. I've never tried to debug deadlocks in Go before.

One other strange thing that I couldn't work out too was promxy was returning an error when one of the two instances in a group was down, but I was under the impression that it should continue working fine- that's for another issue though. It's very difficult to actually tell which instances in each server_group are up or not so some more debug logging or metrics to expose that would be great

**Comment by jacksontj** [comment]
First off, thanks for the report! I have noticed some unresponsiveness in startup, but haven't run into a deadlock (and I actually use consul a LOT) so definitely curious to track this one down.

Promxy actually has the pprof plugin () enabled, so if you have it running you can go to `http://localhost:8082/debug/pprof/` on the promxy instance to get insight into whats happening. The easiest to look at is the goroutine dump which will include what every goroutine is doing (which should make it trivial to find a deadlock). So if you can't figure it out from that data, I'd suggest grabbing a few of those goroutine dumps spread out over a couple of minutes and upload them and I can take a look.

As for the failure mode, you are correct -- if there are 2 servers in the ServerGroup and one is alive promxy should continue along (if promxy is unable to get data for a servergroup entirely it will by default error the entire response).

**Comment by jacksontj** [comment]
I can reproduce the symptoms you are seeing -- although I'm not certain that the cause is the same exactly. I just started a local consul agent in `dev` mode with the config you provided. After doing so I get the following log lines:


```
{"caller":"consul.go:360","discovery":"consul","err":"Unexpected response code: 500 (No path to datacenter)","level":"error","msg":"Error refreshing service list","ts":"2020-05-30T05:24:10.639Z"}
{"caller":"consul.go:360","discovery":"consul","err":"Unexpected response code: 500 (No path to datacenter)","level":"error","msg":"Error refreshing service list","ts":"2020-05-30T05:24:10.639Z"}
```

And after hacking in a pprof endpoint that starts at the top of main I can see that this is because the ServerGroup load hasn't completed. The initial ApplyConfig() call will only return once the ServerGroups are done applying (or are cancelled). In this case the consul SD won't complete, so the servergroup is never marked as Ready -- so the ApplyConfig never returns. So the general case that I'm showcasing here is that if the servergroups can't load for w/e reason (usually service discovery issue) promxy won't complete startup. 

Now in your specific scenario your logs didn't include anything obvious about consul discovery issues -- but I believe it is the same scenario. If I change your config to: 

``` yaml
global:
  evaluation_interval: 60s
  scrape_interval: 60s
  scrape_timeout: 20s
promxy:
  server_groups:
  - consul_sd_configs:
    - server: localhost:8500
      datacenter: dc1
      services:
      - prometheus-rack
      tags:
      - sw00.sfo07
  - consul_sd_configs:
    - server: localhost:8500
      datacenter: dc1
      services:
      - prometheus-rack
      tags:
      - sw01.sfo07
```

 (just change datacenter to dc1 which by default exists) I now have a config which doesn't match any hosts -- and in this scenario promxy just sits there on an empty terminal not starting properly. So I believe the issue is you have a servergroup (sw01.sfo07 based on the logs) which isn't returning any hosts -- so the servergroup isn't loading properly. So to unblock the issue it seems that you just don't have targets in the consul group defined there.

The secondary issue here are is how to log which servergroups are stuck and #314 will take care of that :)
