### ISSUE TITLE
ALERTS query is empty

### ISSUE THREAD

**Issue by sagor999** [jacksontj/promxy#324]
Hi,

Was trying to import alerts into grafana page.
Regular prometheus supports `ALERTS` query, that shows all active alerts.
But it seems like promxy doesn't support it? 
Was wondering if it would be possible to add support for it? 

Thank you!

**Comment by jacksontj** [comment]
Thanks for reaching out! the `ALERTS` query is actually just quering timeseries with the name `ALERTS` (prometheus creates these by default when rule processing). Promxy itself doesn't directly store these results though, so if you want to capture these you'll need to configure a [remote_write endpoint](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L25). If you don't have something that can accept and store those writes I have a [remote_write exporter](https://github.com/jacksontj/promxy/blob/master/cmd/remote_write_exporter/main.go) in this same repo just for this use-case!

**Comment by sagor999** [comment]
Hm. But I do have remote_write configured using your remote_write_exporter container:
```
      - name: promxy-remote-write
        image: quay.io/jacksontj/promxy:v0.0.59
        imagePullPolicy: IfNotPresent
        args:
          - "--metric-ttl=1m"
          - "--bind-addr=:8083"
          - "--write-path=/receive"
          - "--write-text-path=/receive_text"
          - "--metrics-path=/metrics"
        command: ["/bin/remote_write_exporter"]
```

```
remote_write:
  - url: http://promxy-ingress-service.hidden.svc.cluster.local:8083/receive
    queue_config:
      capacity: 5000
      max_samples_per_send: 500
```

Is there something else missing? 
Thank you!
