### ISSUE TITLE
Missing metrics are not filled from other serves in server group

### ISSUE THREAD

**Issue by oOHenry** [jacksontj/promxy#325]
Hi,

I have two Victoria Metrics clusters in two dcs, each has two nodes. Each dc has the same data.
Promxy config:
```yaml
---
global:
  evaluation_interval: 1m
  external_labels:
    source: promxy
promxy:
  server_groups:
  - static_configs:
    - targets:
      - <virtual ip of dc1>:8481
      - <virtual ip of dc2>:8481
    path_prefix: "/select/0/prometheus/"
    anti_affinity: 10s
    remote_read: true
    query_params:
      nocache: 1
    http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
````
Today one node had a hardware failure and I discovered that the history isn't filled from the other dc, see image below:

![image](https://user-images.githubusercontent.com/16702685/87674416-42dbf080-c776-11ea-946a-d868b16298ce.png)

The node crashed at 14.05 o'clock. Maybe this is a special case, because if a node from victoria metrics is down the remaining node answers but not with the full data.

**Comment by oOHenry** [comment]
I think a possible workaround would be to add all nodes of all dcs to the server group. 
The disadvantage of this would be that all data is queried twice.

**Comment by jacksontj** [comment]
Based on your initial report it sounds like you have 2x2 servers (2 servers in each of 2 DCs) that all have the same data-- meaning you have 4 servers with the same data. In that scenario these graphs don't quite make sense, as DC1 and DC2 both (1) have no holes and (2) don't match.

So maybe the issue with the HW failure just caused some metrics to be under-counted but still represented?

The merging logic in proxy will basically (huge oversimplification) query all nodes in a servergroup; then starting with the first to respond fill any "holes" (determined by the anti_affinity config) with data from the other nodes in the group.

From the graphs you provided above it seems that promxy did what I'd expect, although I imagine this means that the setup is not quite as described. My guess from this is that DC1 has 2 nodes that match and DC2 has 2 nodes that match, but DC1 data != DC2. If thats the case the config should look something like:


``` yaml
global:
  evaluation_interval: 1m
  external_labels:
    source: promxy
promxy:
  server_groups:
  - static_configs:
    - targets:
      - dc1host1:8481
      - dc1host2:8481
    path_prefix: "/select/0/prometheus/"
    anti_affinity: 10s
    remote_read: true
    query_params:
      nocache: 1
    http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
    labels:
      dc: "1"
  - static_configs:
    - targets:
      - dc2host1:8481
      - dc2host2:8481
    path_prefix: "/select/0/prometheus/"
    anti_affinity: 10s
    remote_read: true
    query_params:
      nocache: 1
    http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
    labels:
      dc: "2"
```


Hopefully thats helpful? Data merging can definitely be a bit confusing; so its entirely possible I missed something -- hopefully thats a helpful start :)
