### ISSUE TITLE
Unable to set flags  --write-path=/receive, --metrics-path=/metrics,  --metric-ttl=1m

### ISSUE THREAD

**Issue by chaets** [jacksontj/promxy#327]
I am running a docker container for promxy, 
```
promxy:
    image: quay.io/jacksontj/promxy:latest
    container_name: promxy
    hostname: insights-promxy
    build:
      context: ../../../../
      dockerfile: /Dockerfile.promxy
    ports:
      - 8082:8082
    volumes:
      - /prometheus/config/:/promxy-config/
    networks:
      main:
        aliases:
          - insights-promxy
    command:
      - --config=/promxy-config/promxy-edge.yml
      - --log-level=info
      - --web.enable-lifecycle
      # - --metric-ttl=1m
      - --bind-addr=:8083
      # - --write-path=/receive
      # - --metrics-path=/metrics
    restart: always
```
firstly it is giving me an error
```
time="2020-07-16T17:47:18Z" level=info msg="promxy starting"
time="2020-07-16T17:47:32Z" level=warning fields.msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed." queue="0:http://insights-promxy:8083/receive"
172.31.254.3 - - [16/Jul/2020 17:47:33] "POST /receive HTTP/1.1 404 19" 0.000709 
```
and when I am enabling the path by enabling different it is giving the error as 

```
(base)chetangupta$ docker logs promxy
unknown flag `metric-ttl'
unknown flag `metric-ttl'
unknown flag `metric-ttl'
unknown flag `metric-ttl'
unknown flag `metric-ttl'
unknown flag `metric-ttl'
unknown flag `metric-ttl'
unknown flag `metric-ttl'
```
when I have checked inside the container it is showing me that the following flags ``` --write-path=/receive, --metrics-path=/metrics,  --metric-ttl=1m ``` is not available

```

/ # ./bin/promxy -help
Usage:
  promxy [OPTIONS]

Application Options:
  -v, --version                                   print out version and exit
      --bind-addr=                                address for promxy to listen on (default: :8082)
      --config=                                   path to the config file (default: config.yaml)
      --log-level=                                Log level (default: info)
      --web.read-timeout=                         Maximum duration before timing out read of the request, and closing idle connections. (default: 5m)
      --web.external-url=                         The URL under which Prometheus is externally reachable (for example, if Prometheus is served via a reverse proxy). Used for generating relative and absolute links back to Prometheus itself. If the URL has a path portion,
                                                  it will be used to prefix all HTTP endpoints served by Prometheus. If omitted, relevant URL components will be derived automatically.
      --web.enable-lifecycle                      Enable shutdown and reload via HTTP request.
      --query.timeout=                            Maximum time a query may take before being aborted. (default: 2m)
      --query.max-concurrency=                    Maximum number of queries executed concurrently. (default: 1000)
      --query.max-samples=                        Maximum number of samples a single query can load into memory. Note that queries will fail if they would load more samples than this into memory, so this also limits the number of samples a query can return. (default:
                                                  50000000)
      --query.lookback-delta=                     The maximum lookback duration for retrieving metrics during expression evaluations. (default: 5m)
      --alertmanager.notification-queue-capacity= The capacity of the queue for pending alert manager notifications. (default: 10000)
      --access-log-destination=                   where to log access logs, options (none, stderr, stdout) (default: stdout)
      --rules.alert.for-outage-tolerance=         Max time to tolerate prometheus outage for restoring for state of alert. (default: 1h)
      --rules.alert.for-grace-period=             Minimum duration between alert and restored for state. This is maintained only for alerts with configured for time greater than grace period. (default: 10m)
      --rules.alert.resend-delay=                 Minimum amount of time to wait before resending an alert to Alertmanager. (default: 1m)
      --http.shutdown-delay=                      time to wait before shutting down the http server, this allows for a grace period for upstreams (e.g. LoadBalancers) to discover the new stopping status through healthchecks (default: 10s)
      --http.shutdown-timeout=                    max time to wait for a graceful shutdown of the HTTP server (default: 60s)

Help Options:
  -h, --help                                      Show this help message
```

can Someone help me what exactly I am missing out? any leads will be highly appreciated.
Thanks
