### ISSUE TITLE
Add option for validate rules and exit

### ISSUE THREAD

**Issue by wf1nder** [jacksontj/promxy#333]
We are currently validating alert rules with prometheus before deploy it to promxy. But today we are faced that prometheus missed some errors, and promxy refused to load them.

I suggest to add something like ```-dryRun``` option to promxy, which will validate recording/alert rules, and exit with appropriate code: 0 if no errors, any other if there are allors in rules. Then we will be able to validate rules by promxy.

**Comment by wf1nder** [comment]
Error example:

```
  - alert: AlertName_Foo
    expr: <some expr>
    for: 2m
    lables:
      job: bar
    annotations:
    ...
```

There are `lables` word instead of `labels`, which prometheus missed. Promxy said:
```
{"caller":"manager.go:793","err":"yaml: unmarshal errors:\n  line 16: field lables not found in type rulefmt.Rule","level":"error","msg":"loading groups failed","ts":"2020-08-05T09:54:17.454Z"}
time="2020-08-05T09:54:17Z" level=error msg="failed to apply configuration: error loading rules, previous rule set restored"
time="2020-08-05T09:54:17Z" level=error msg="Error reloading config: one or more errors occurred while applying new configuration" source="main.go:423"
```

**Comment by jacksontj** [comment]
Upstream prometheus actually provides a tool (`promtool`) that does this. Some details can be found in the upstream docs: https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/

Given that promxy has no changes to the alerting rule structure it seems that promtool should be sufficient :)

**Comment by wf1nder** [comment]
Excuse me, I misled you. Yes, we are now validating alerts by promtool.

Here is the alert rule file entirely:

```
groups:
- name: Some alert rule
  rules:
  - alert: AlertName_Foo
    expr: up
    for: 2m
    lables:
      job: bar
    annotations:
      description: some description
```
There is an error, `lables` instead of `labels`.
promtool doesn't see an error:
```
# ./promtool check rules alerts/foo.yml && echo $?
Checking alerts/foo.yml
  SUCCESS: 1 rules found

0
```

But promxy can't start or reload with that rule file:
```
# ./promxy-v0.0.60-linux-amd64 --config=promxy.yml
{"caller":"manager.go:793","err":"yaml: unmarshal errors:\n  line 7: field lables not found in type rulefmt.Rule","level":"error","msg":"loading groups failed","ts":"2020-08-06T06:39:18.390Z"}
ERRO[2020-08-06T09:39:18+03:00] failed to apply configuration: error loading rules, previous rule set restored
FATA[2020-08-06T09:39:18+03:00] Error loading config: one or more errors occurred while applying new configuration
```

Fixing `lables` to `labels` also fixes promxy:
```
# ./promxy-v0.0.60-linux-amd64 --config=promxy.yml
WARN[2020-08-06T09:39:56+03:00] Alerting rules are configured but no remote_write endpoint is configured.
INFO[2020-08-06T09:39:56+03:00] promxy starting
```
