### ISSUE TITLE
Missing metrics are not filled from other serves in server group #2

### ISSUE THREAD

**Issue by matejzero** [jacksontj/promxy#337]
Hello,

I first wanted to add my case under https://github.com/jacksontj/promxy/issues/325, but it seems our cases are not exactly the same as the end result is different, but the title matches my case. Feel free to change it if you can think of a better one.

My case:
I have one Prometheus in DC1 and one Prometheus in DC2. Same goes for VictoriaMetrics. Prometheus is doing a cross-dc scraping and feeding data to local VictoriaMetrics server. I'm using Promxy to deduplicate and fill data.

Schema:
![Screenshot 2020-08-18 at 11 06 57](https://user-images.githubusercontent.com/4689252/90493698-f738b000-e142-11ea-8162-4862a760a5de.png)
 
Today I upgraded my VM instances and while one was restarting, I got a hole in my graph even though the other one was able to provide data. But the end result was a graph with holes in it.

Example:
![Screenshot 2020-08-18 at 11 17 29](https://user-images.githubusercontent.com/4689252/90495040-6c58b500-e144-11ea-86dc-6c64e6f33200.png)

The first graph is the restarted victoriametric server, the second one was running at the time and the third one is the result from Promxy.

Promxy config (my scraping interval is 10s):
```yaml
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy
rule_files:
  - "*rule"
promxy:
  server_groups:
    - static_configs:
        - targets:
          - vm-dc1:8428
          - vm-dc2:8428
      labels:
        sg: prometheus
      anti_affinity: 10s
      remote_read: true
      remote_read_path: api/v1/read
      query_params:
        nocache: 1
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
```

Is this a bug or iz my config / understanding wrong?
