### ISSUE TITLE
Unable to get metrics data from Prometheus

### ISSUE THREAD

**Issue by CyberMaax** [jacksontj/promxy#339]
Hello, I'm trying to use Promxy for several days, to aggregate two Prometheus instance with exactly the same config, and send the data to another tool (Kafka or Cortex) with only one source.

Here is my Promxy config:
```yaml
remote_write:
  - url: http://kafka/promxy-test
promxy:
  server_groups:
    - static_configs:
        - targets:
          - prometheus:9090
          - prometheus2:9090
      labels:
        sg: test
      anti_affinity: 10s
      remote_read: true
      remote_read_path: /api/v1/read
      query_params:
        nocache: 1
      scheme: http
      http_client:
        dial_timeout: 10s
        tls_config:
          insecure_skip_verify: true
```
I get the label name, but not metrics data.
I can see all labels name on Promxy web interface, but i'm unable to make any queries.

Here is the logs from Promxy:
```
time="2020-08-20T09:27:45Z" level=debug msg="Updating targets from discovery manager"
time="2020-08-20T09:27:45Z" level=debug msg="Updating targets from discovery manager: [prometheus:9090 prometheus2:9090]"
time="2020-08-20T09:27:45Z" level=debug msg="Servergroup 0 taking a long time to be Ready (still waiting)"
time="2020-08-20T09:27:45Z" level=info msg="promxy starting"
172.25.0.1 - - [20/Aug/2020 09:27:49] "GET /graph HTTP/1.1 200 4850" 0.001969
172.25.0.1 - - [20/Aug/2020 09:27:49] "GET /static/js/graph/graph_template.handlebar HTTP/1.1 200 7946" 0.000513 v=&_=1597915684428
172.25.0.1 - - [20/Aug/2020 09:27:50] "GET /api/v1/query HTTP/1.1 200 104" 0.000580 _=1597915684429&query=time%28%29
time="2020-08-20T09:27:50Z" level=debug msg="http://prometheus2:9090/api/v1/read" api=LabelValues label=__name__
time="2020-08-20T09:27:50Z" level=debug msg="http://prometheus:9090/api/v1/read" api=LabelValues label=__name__
time="2020-08-20T09:27:50Z" level=debug msg="http://prometheus2:9090/api/v1/read" api=LabelValues label=__name__ took=4.998671ms
time="2020-08-20T09:27:50Z" level=debug msg="http://prometheus:9090/api/v1/read" api=LabelValues label=__name__ took=5.512048ms
time="2020-08-20T09:27:50Z" level=debug msg=LabelValues name=__name__ took=6.501251ms
172.25.0.1 - - [20/Aug/2020 09:27:50] "GET /api/v1/label/__name__/values HTTP/1.1 200 3706" 0.007708 _=1597915684430
time="2020-08-20T09:27:54Z" level=debug msg="VectorSelector: up"
time="2020-08-20T09:27:54Z" level=debug msg="http://prometheus2:9090/api/v1/read" api=Query query=up ts="2020-08-20 09:28:08.596 +0000 UTC"
time="2020-08-20T09:27:54Z" level=debug msg="http://prometheus2:9090/api/v1/read" api=Query query=up took="9.752µs" ts="2020-08-20 09:28:08.596 +0000 UTC"
time="2020-08-20T09:27:54Z" level=debug msg="http://prometheus:9090/api/v1/read" api=Query query=up ts="2020-08-20 09:28:08.596 +0000 UTC"
time="2020-08-20T09:27:54Z" level=debug msg="http://prometheus:9090/api/v1/read" api=Query query=up took="6.191µs" ts="2020-08-20 09:28:08.596 +0000 UTC"
172.25.0.1 - - [20/Aug/2020 09:27:54] "GET /api/v1/query HTTP/1.1 200 87" 0.000625 query=up&time=1597915688.596&_=1597915684431
```
Am I doing something wrong?
Thank you in advance for your help.
