### ISSUE TITLE
Targets is unavailable

### ISSUE THREAD

**Issue by Posya** [jacksontj/promxy#343]
Hi!

I created three docker containers with 2 Prometheus and 1 Promxy
``` docker-compose.yaml
version: "3"
services:
  prom1:
    container_name: prom1
    hostname: prom1
    image: prom/prometheus

  prom2:
    container_name: prom2
    hostname: prom2
    image: prom/prometheus

  promxy:
    container_name: promxy
    hostname: promxy
    image: quay.io/jacksontj/promxy
    volumes:
      - ~/promxy.yaml:/etc/promxy/config.yaml
    command:
      - --config=/etc/promxy/config.yaml
      - --log-level=debug
    ports:
      - "8082:8082"
    depends_on:
      - prom1
      - prom2
```

This is promxy/config.yaml :
```
global:
  evaluation_interval: 5s
  source: promxy

promxy:
  server_groups:
    - static_configs:
        - targets:
          - prom1:9090
          - prom2:9090
      labels:
        sg: test
```

I can see targets in prometheus web pages, but promxy targets page is empty...

Why?

I see this in promxy logs:
```
promxy    | time="2020-09-07T15:25:52Z" level=debug msg="Servergroup 0 taking a long time to be Ready (still waiting)"
promxy    | time="2020-09-07T15:25:52Z" level=debug msg="Updating targets from discovery manager"
promxy    | time="2020-09-07T15:25:52Z" level=debug msg="Updating targets from discovery manager: [prom1:9090 prom2:9090]"
promxy    | time="2020-09-07T15:25:52Z" level=info msg="promxy starting"
```
