### ISSUE TITLE
Promxy returning empty results intermittently

### ISSUE THREAD

**Issue by ottoyiu** [jacksontj/promxy#362]
Perhaps related to #355.

We are using Promxy as a kubernetes cluster-wide aggregator of multiple discrete Prometheus deployments within the cluster. 

Promxy is currently configured to retrieve metrics from two separate server groups via promql using `/api/v1/query_range` rather than remote reads (ie. `remote_read: False`).

Each server group is discovering a service that points to Thanos Querier Frontends (a caching proxy infront of Thanos Querier).

In this example, I have two prometheus deployments that I want to aggregate using Promxy. One deployment is `example` in the `dev-jsiaw` namespace, and the other is `oyiu-pipe` in the `oyiu-pipe` namespace.

Config:
```
  config.yaml: |
    global:
      evaluation_interval: 5s
      external_labels:
        source: promxy
    promxy:
      server_groups:
      - kubernetes_sd_configs:
        - namespaces:
            names:
            - dev-jsiaw
          role: endpoints
        labels:
          pipeline_name: example
          pipeline_namespace: dev-jsiaw
        relabel_configs:
        - action: keep
          regex: ^example-thanos-query-frontend$
          separator: ;
          source_labels:
          - __meta_kubernetes_endpoints_name
        - action: keep
          regex: ^http$
          separator: ;
          source_labels:
          - __meta_kubernetes_endpoint_port_name
        remote_read: false
        ignore_error: true
      - kubernetes_sd_configs:
        - namespaces:
            names:
            - oyiu-pipe
          role: endpoints
        labels:
          pipeline_name: oyiu-pipe
          pipeline_namespace: oyiu-pipe
        relabel_configs:
        - action: keep
          regex: ^oyiu-pipe-thanos-query-frontend$
          separator: ;
          source_labels:
          - __meta_kubernetes_endpoints_name
        - action: keep
          regex: ^http$
          separator: ;
          source_labels:
          - __meta_kubernetes_endpoint_port_name
        ignore_error: true
        remote_read: false
    remote_write: []
    rule_files:
    - '*rule'
```

When requesting range queries, Promxy returns an empty result even though the Thanos Query Frontend returns a proper result. This occurs 6/10 times. It happens even more frequent on larger range queries.

Example query: go_memstats_gc_cpu_fraction{pipeline_name="example"}

Promxy:
```
{

    "status": "success",
    "data": {
        "resultType": "matrix",
        "result": [ ]
    }

}
```

vs Thanos Query Frontend:
```

{

    "status": "success",
    "data": {
        "resultType": "matrix",
        "result": [
            {
                "metric": {
                    "__name__": "go_memstats_gc_cpu_fraction",
                    "instance": "10.79.1.124:10902",
                    "job": "pods-nginx",
                    "kubernetes_namespace": "dev-jsiaw",
                    "kubernetes_pod_name": "example-thanos-query-frontend-86dcdf565d-lp9ms",
                    "pipeline_name": "example",
                    "pipeline_namespace": "dev-jsiaw",
                    "receive_replica": "example-thanos-receiver-0",
                    "tenant_id": "dev-jsiaw-example"
                },
                "values": [
                    [
                        1604612203,
                        "0.000053259467817038186"
                    ],
                  ...
}
```

Diving into the code, I've added debugging messages and see that the PromAPIV1 and MultiAPI `QueryRange` calls do succeed , and contain the proper result that is returned by the Thanos Query Frontend. However, the returned results is empty from Promxy's api/v1/query_range call.

 ProxyStorage.NodeReplacer also is seen to properly getting the results back from `state.client.QueryRange` and set the Series properly:
https://github.com/jacksontj/promxy/blob/9012d2833f6d1960a1406bd531f716c498036b3f/pkg/proxystorage/proxy.go#L515-L536

At this point, I'm lost in the code to dive further. Any help would be appreciated it!
