### ISSUE TITLE
Promxy unable to connect to thanos querier

### ISSUE THREAD

**Issue by gidesh** [jacksontj/promxy#366]
Im trying to connect to thanos querier from promxy to fill the gaps thanos querier causes when prometheus restarts sometimes.

Following is the config
```
    promxy:
      server_groups:
        - static_configs:
            - targets:
              - thanos-query.platform.svc.cluster.local
          anti_affinity: 10s
          query_params:
            nocache: 1
          http_client:
            dial_timeout: 1s
            tls_config:
              insecure_skip_verify: true
```

Trying to connect thanos querier through the k8s svc DNS. It fails with the following error when I check promxy UI

```
Error executing query: Post "http://thanos-query.platform.svc.cluster.local/api/v1/query?nocache=1": dial tcp 10.128.31.143:80: i/o timeout
```

Any help is highly appreciated. Thanks
