### ISSUE TITLE
Promxy do not aggregate sum and count functions

### ISSUE THREAD

**Issue by niaurys** [jacksontj/promxy#368]
In our infrastructure we have implemented Prometheus [Horizontal Sharding](https://www.robustperception.io/scaling-and-federating-prometheus) without leader, and we would like to use Promxy to query all Prometheus for metrics as well as use Promxy for alerting.

However, there is strange behaviour with some functions, in particular with `sum()` and `count()` as they are returning not aggregated results. I was able to reproduce behaviour locally in Docker. I am running two Prometheus instances, which scrapes themselfs:

docker-compose.yml:
```
version: '3.2'
services:
  prometheus1:
    image: prom/prometheus:v2.23.0
    container_name: prometheus1
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus1.yml:/etc/prometheus/prometheus.yml:ro
  prometheus2:
    image: prom/prometheus:v2.23.0
    container_name: prometheus2
    ports:
    - 9190:9190
    command:
    - --web.listen-address=:9190
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus2.yml:/etc/prometheus/prometheus.yml:ro
```
prometheus1.yml:
```
global:
  scrape_interval: 5s

scrape_configs:
- job_name: prometheus1
  scrape_timeout: 5s
  static_configs:
  - targets:
    - prometheus1:9090
```
prometheus2.yml:
```
global:
  scrape_interval: 5s

scrape_configs:
- job_name: prometheus2
  scrape_timeout: 5s
  static_configs:
  - targets:
    - prometheus2:9190
```
I also run Promxy (v0.0.62) in Docker:
```
docker run --publish 8082:8082 -v /Users/niaurys/dev/promxy:/cmd promxy:0.0.62 --config=/cmd/config.yaml --log-level=trace
```
So with everything running, I am querying Promxy for `up{}` metrics `curl -g 'http://localhost:8082/api/v1/query?query=up'`. The result is correct and two metrics are returned correctly:
```json
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "up",
          "instance": "prometheus1:9090",
          "job": "prometheus1"
        },
        "value": [
          1606901285.893,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "up",
          "instance": "prometheus2:9190",
          "job": "prometheus2"
        },
        "value": [
          1606901285.893,
          "1"
        ]
      }
    ]
  }
}
```
And if I want to have `sum()` over these metrics `curl -g 'http://localhost:8082/api/v1/query?query=sum(up)'`, the result is incorrect (returns 1).
```json
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {},
        "value": [
          1606901399.763,
          "1"
        ]
      }
    ]
  }
}
```

Here are Promxy logs with these two queries, where `sum(up)` is the second query. It seems Promxy was able to get `sum(up)` from both servers correctly.
```
time="2020-12-02T09:08:31Z" level=debug msg="Servergroup 0 taking a long time to be Ready (still waiting)"
time="2020-12-02T09:08:31Z" level=debug msg="Updating targets from discovery manager"
time="2020-12-02T09:08:31Z" level=trace msg="Potential target pre-relabel: {__address__=\"192.168.88.26:9190\"}"
time="2020-12-02T09:08:31Z" level=trace msg="Potential target post-relabel: {__address__=\"192.168.88.26:9190\"}"
time="2020-12-02T09:08:31Z" level=debug msg="Updating targets from discovery manager: [192.168.88.26:9190]"
time="2020-12-02T09:08:31Z" level=debug msg="Updating targets from discovery manager"
time="2020-12-02T09:08:31Z" level=trace msg="Potential target pre-relabel: {__address__=\"192.168.88.26:9090\"}"
time="2020-12-02T09:08:31Z" level=trace msg="Potential target post-relabel: {__address__=\"192.168.88.26:9090\"}"
time="2020-12-02T09:08:31Z" level=debug msg="Updating targets from discovery manager: [192.168.88.26:9090]"
time="2020-12-02T09:08:31Z" level=info msg="promxy starting"
time="2020-12-02T09:08:41Z" level=debug msg="VectorSelector: up"
time="2020-12-02T09:08:41Z" level=debug msg="http://192.168.88.26:9190" api=Query query=up ts="2020-12-02 09:08:41.805 +0000 UTC"
time="2020-12-02T09:08:41Z" level=debug msg="http://192.168.88.26:9090" api=Query query=up ts="2020-12-02 09:08:41.805 +0000 UTC"
time="2020-12-02T09:08:41Z" level=trace msg="http://192.168.88.26:9090" api=Query error="<nil>" query=up took=7.709031ms ts="2020-12-02 09:08:41.805 +0000 UTC" value="up{instance=\"prometheus1:9090\", job=\"prometheus1\"} => 1 @[1606900121.805]" warnings="[]"
time="2020-12-02T09:08:41Z" level=trace msg="http://192.168.88.26:9190" api=Query error="<nil>" query=up took=8.632781ms ts="2020-12-02 09:08:41.805 +0000 UTC" value="up{instance=\"prometheus2:9190\", job=\"prometheus2\"} => 1 @[1606900121.805]" warnings="[]"
172.17.0.1 - - [02/Dec/2020 09:08:41] "GET /api/v1/query HTTP/1.1 200 170" 0.011832 query=up%7B%7D&time=1606900121.805&_=1606900026529
time="2020-12-02T09:08:51Z" level=debug msg="AggregateExpr sum(up) sum"
time="2020-12-02T09:08:51Z" level=debug msg="http://192.168.88.26:9190" api=Query query="sum(up)" ts="2020-12-02 09:08:51.417 +0000 UTC"
time="2020-12-02T09:08:51Z" level=debug msg="http://192.168.88.26:9090" api=Query query="sum(up)" ts="2020-12-02 09:08:51.417 +0000 UTC"
time="2020-12-02T09:08:51Z" level=trace msg="http://192.168.88.26:9090" api=Query error="<nil>" query="sum(up)" took=5.152491ms ts="2020-12-02 09:08:51.417 +0000 UTC" value="{} => 1 @[1606900131.417]" warnings="[]"
time="2020-12-02T09:08:51Z" level=trace msg="http://192.168.88.26:9190" api=Query error="<nil>" query="sum(up)" took=5.27573ms ts="2020-12-02 09:08:51.417 +0000 UTC" value="{} => 1 @[1606900131.417]" warnings="[]"
172.17.0.1 - - [02/Dec/2020 09:08:51] "GET /api/v1/query HTTP/1.1 200 120" 0.011562 query=sum%28up%7B%7D%29&time=1606900131.417&_=1606900026530
```

I was able to workaround the issue by adding additional labels in server groups (https://github.com/jacksontj/promxy/blob/v0.0.62/cmd/promxy/config.yaml#L39-L40), but if it is possible I would like to avoid using them.

With all presented above, do I run Promxy incorrectly and where is some configuration issue? Or where is some bug in aggregation logics?

Let me know if any more information is needed.
