### ISSUE TITLE
/Targets page does not show targets.

### ISSUE THREAD

**Issue by rsvancara** [jacksontj/promxy#369]
I see where this has been a challenge noted in other issues, but I have not been able to find a clear answer to my problem.  When I visit the /targets page in the prometheus Web client included in promxy, i can not see any targets listed.  See attached image.

Steps to Produce:
1.  Configured prometheus to ship logs to VictoriaMetrics.  Configured Promxy to access the VictoriaMetrics server.  We have two victoriametrics servers with identical data (mostly).  I visit the url:  http://server:8082/targets and the page loads no content other than the navigation controls.  See attached image.  
![Screen Shot 2020-12-15 at 5 29 00 PM](https://user-images.githubusercontent.com/322753/102294226-ac1a8800-3efd-11eb-8f64-d37ed5b81d43.png)

2. Versions:
prometheus, version 2.22.0 (branch: HEAD, revision: 0a7fdd3b76960808c3a91d92267c3d815c1bc354)
  build user:       root@6321101b2c50
  build date:       20201015-12:29:59
  go version:       go1.15.3
  platform:         linux/amd64

Promxy:
Version v0.0.62

Victoria Metrics:
victoria-metrics-20201107-155439-tags-v1.46.0-0-g41813eb87

3.  Configuration

````
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy

rule_files:
- "*rule"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:12345"

remote_write:
  - url: http://localhost:8428/api/v1/write

promxy:
  server_groups:
    - static_configs:
        - targets:
          - 10.204.2.95:8428
          - 10.204.5.77:8428
      labels:
        sg: localhost_8428
      anti_affinity: 10s
      remote_read: true
      remote_read_path: api/v1/read
      query_params:
        nocache: 1
      scheme: http
      http_client:
        dial_timeout: 1s
````

Please let me know if I can provide more information.  I was digging through some of the code for the project but it was unclear to me as to where to even look. 

Randall
