### ISSUE TITLE
panic after upgrading from 0.0.62 to 0.0.66

### ISSUE THREAD

**Issue by Wing924** [jacksontj/promxy#386]
```
panic: WHAT

goroutine 1 [running]:
github.com/jacksontj/promxy/pkg/proxystorage.(*ProxyStorage).ApplyConfig(0xc000cc8bc0, 0xc0002fe870, 0xc0002fe870, 0x0)
	/go/src/github.com/jacksontj/promxy/pkg/proxystorage/proxy.go:123 +0x6fa
main.reloadConfig(0xc000cc07f0, 0xc000124280, 0x5, 0x8, 0x8, 0x30ff420)
	/go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:117 +0xb4
main.main()
	/go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:384 +0x18fc
```

my config:
```yaml
global:
  evaluation_interval: 15s
  external_labels:
    prometheus: test-promxy
    prometheus_replica: test-promxy-0

rule_files:
  - /rules/*.yml
remote_write:
  - name: cortex
    url: https://tenant1.cortex.local/api/prom/push
    bearer_token_file: /secret/token
    queue_config:
      batch_send_deadline: 5s
      capacity: 20000
      max_backoff: 500ms
      max_samples_per_send: 4000
      max_shards: 100
      min_backoff: 30ms
      min_shards: 1

promxy:
  server_groups:
    - static_configs:
        - targets: [tenant1.cortex.local]
          labels:
            _tenant: tenant1
      scheme: https
      path_prefix: /prometheus
    - static_configs:
        - targets: [tenant2.cortex.local]
          labels:
            _tenant: tenant2
      scheme: https
      path_prefix: /prometheus
```
