### ISSUE TITLE
api/v1/series query is broken in 0.0.67

### ISSUE THREAD

**Issue by sagor999** [jacksontj/promxy#395]
Hi,

I was trying to upgrade from 0.0.62 to 0.0.67, but noticed that my grafana dashboards got broken when switched to 0.67.
It seems like this query is no longer working properly in 0.0.67:
```
https://promxy2.example.com/api/v1/series?match%5B%5D=elasticsearch_cluster_health_status&start=1613643282&end=1613686482
```
It returns: 
```
{"status":"success","data":[]}
```
In 0.0.62 same query returns correct data:
```
{
  "status": "success",
  "data": [
    {
      "__name__": "elasticsearch_cluster_health_status",
      "cluster": "elasticsearch",
      "color": "red",
      "endpoint": "http",
      "instance": "192.168.46.179:9108",
      "job": "elasticsearch-exporter-prometheus-elasticsearch-exporter",
      "namespace": "elastic",
      "pod": "elasticsearch-exporter-prometheus-elasticsearch-exporter-65q2kn",
      "prometheus": "cluster-prometheus-prometh-prometheus",
      "promxy": "prometheus.example.com",
      "service": "elasticsearch-exporter-prometheus-elasticsearch-exporter",
    },
    {
      "__name__": "elasticsearch_cluster_health_status",
      "cluster": "elasticsearch",
      "color": "yellow",
      "endpoint": "http",
      "instance": "192.168.46.179:9108",
      "job": "elasticsearch-exporter-prometheus-elasticsearch-exporter",
      "namespace": "elastic",
      "pod": "elasticsearch-exporter-prometheus-elasticsearch-exporter-65q2kn",
      "prometheus": "cluster-prometheus-prometh-prometheus",
      "promxy": "prometheus.example.com",
      "service": "elasticsearch-exporter-prometheus-elasticsearch-exporter",
    }
}
```

Thank you!

**Comment by jacksontj** [comment]
This is actually curious; I did just set up a local promxy pointing at a demo prometheus and I seem to get results just fine with 0.0.67 as well as master. My configs below:

``` yaml
##
## Regular prometheus configuration
##
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy


##
### Promxy configuration
##
promxy:
  server_groups:
    # as many additional server groups as you have
    - static_configs:
        - targets:
          - demo.robustperception.io:9090
      labels:
        sg: localhost_9091
      anti_affinity: 10s
      scheme: http
      http_client:
        tls_config:
          insecure_skip_verify: true
```

URL: `http://localhost:8082/api/v1/series?match[]=node_procs_blocked&start=1613643282&end=1613686482`
Result:
``` json
{

    "status": "success",
    "data": [
        {
            "__name__": "node_procs_blocked",
            "instance": "demo.robustperception.io:9100",
            "job": "node",
            "sg": "localhost_9091"
        }
    ]

}
```


So hopefully that helps narrow down the issue. If not could you include your config file and trace log output?
