### ISSUE TITLE
Seeing slower query response

### ISSUE THREAD

**Issue by dileepranganathan** [jacksontj/promxy#396]
**Issue**
Thank you for this project. This is very useful for our usecase. We are currently evaluating it in our staging cluster. 
We are running promxy v0.0.67 in kubernetes. Currently we are seeing slower query response time while querying via promxy compared to directly querying downstream prometheus. Am I missing any configuration related to this here?

**Setup/Config**
```
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy

promxy:
  server_groups:
  - static_configs:
      - targets:
        - prometheus1.myserver.com
    anti_affinity: 10s
    remote_read: true
    remote_read_path: api/v1/read
    scheme: https
    http_client:
      dial_timeout: 2s
      tls_config:
        insecure_skip_verify: true
    ignore_error: true
```

**Promxy Logs**
```
time="2021-02-19T00:14:29Z" level=debug msg="VectorSelector: avalanche_metric_mmmmm_8_0"
time="2021-02-19T00:14:29Z" level=debug msg="https://prometheus1.myserver.com/api/v1/read" api=QueryRange query=avalanche_metric_mmmmm_8_0 r="{2021-02-17 02:10:37.263 +0000 UTC 2021-02-17 03:10:37.263 +0000 UTC 14s}"
time="2021-02-19T00:14:30Z" level=debug msg="https://prometheus1.myserver.com/api/v1/read" api=QueryRange query=avalanche_metric_mmmmm_8_0 r="{2021-02-17 02:10:37.263 +0000 UTC 2021-02-17 03:10:37.263 +0000 UTC 14s}" took=559.626019ms
127.0.0.1 - - [19/Feb/2021 00:14:30] "GET /api/v1/query_range HTTP/1.1 200 3870996" 0.665657 end=1613531437.263&step=14&_=1612476589553&query=avalanche_metric_mmmmm_8_0&start=1613527837.263
10.233.65.1 - - [19/Feb/2021 00:14:31] "GET /-/healthy HTTP/1.1 200 23" 0.000115 
```

**Observed Results**
Note: I tried to curl within the same promxy pod to rule out any kubernetes networking issues.

Querying via promxy from within promxy pod
```
/tmp $ curl -w "@curl-format.txt" -o /dev/null -s 'http://localhost:8082/api/v1/query_range?query=avalanche_metric_mmmmm_8_0&start=1613527837.263&end=1613531437.263&step=14&_=1612476589553'
     time_namelookup:  0.000483s
        time_connect:  0.000607s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000668s
       time_redirect:  0.000000s
  time_starttransfer:  0.665167s
                      ----------
          time_total:  0.666732s
```

Querying directly to prometheus from within promxy pod
```
/tmp $ curl -w "@curl-format.txt" -o /dev/null -s 'https://prometheus1.myserver.com/api/v1/query_range?query=avalanche_metric_mmmmm_8_0&start=1613527837.263&end=1613531437.263&step=14&_=1612476589553' -k
     time_namelookup:  0.001204s
        time_connect:  0.001919s
     time_appconnect:  0.027187s
    time_pretransfer:  0.027246s
       time_redirect:  0.000000s
  time_starttransfer:  0.236186s
                      ----------
          time_total:  0.260054s
```
