### ISSUE TITLE
Seeing empty results for Subquery - exceeded maximum resolution of 11,000 

### ISSUE THREAD

**Issue by dileepranganathan** [jacksontj/promxy#403]
**Issue**
Seeing empty results with error`error="bad_data: exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)"` when executing promql expressions with subqueries. The same query works in prometheus for eg: http://demo.robustperception.io:9090/graph?g0.expr=avg_over_time((sum%20by%20(cpu)%20(node_cpu_guest_seconds_total))%5B1w%3A%5D)&g0.tab=0&g0.stacked=0&g0.range_input=1w

**Query Used** 
query_range with 7d interval
`avg_over_time((sum by (cpu) (node_cpu_guest_seconds_total))[1w:])`

**Setup/Config**
Prometheus server :  http://demo.robustperception.io:9090
```
##
## Regular prometheus configuration
##
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy

# remote_write configuration is used by promxy as its local Appender, meaning all
# metrics promxy would "write" (not export) would be sent to this. Examples
# of this include: recording rules, metrics on alerting rules, etc.
remote_write:
  - url: http://localhost:8083/receive

##
### Promxy configuration
##
promxy:
  server_groups:
    - static_configs:
        - targets:
            - demo.robustperception.io:9090
      labels:
        cluster: demo
      anti_affinity: 10s
      remote_read: false
      remote_read_path: api/v1/read
      scheme: http
      http_client:
        dial_timeout: 30s
        tls_config:
          insecure_skip_verify: true
      ignore_error: true

```
**Promxy Trace Logs**
```
DEBU[2021-03-15T16:27:11-07:00] Updating targets from discovery manager      
DEBU[2021-03-15T16:27:11-07:00] Servergroup 0 taking a long time to be Ready (still waiting) 
TRAC[2021-03-15T16:27:11-07:00] Potential target pre-relabel: {__address__="demo.robustperception.io:9090", __path_prefix__="", __scheme__="http"} 
TRAC[2021-03-15T16:27:11-07:00] Potential target post-relabel: {__address__="demo.robustperception.io:9090", __path_prefix__="", __scheme__="http"} 
DEBU[2021-03-15T16:27:11-07:00] Updating targets from discovery manager: [demo.robustperception.io:9090] 
INFO[2021-03-15T16:27:11-07:00] promxy starting                              
DEBU[2021-03-15T16:27:13-07:00] SubqueryExpr: (sum by(cpu) (node_cpu_guest_seconds_total))[1w:] 
DEBU[2021-03-15T16:27:13-07:00] AggregateExpr sum by(cpu) (node_cpu_guest_seconds_total) sum 
DEBU[2021-03-15T16:27:13-07:00] http://demo.robustperception.io:9090          api=QueryRange query="sum by(cpu) (node_cpu_guest_seconds_total)" r="{2021-03-01 23:27:10 +0000 UTC 2021-03-15 23:27:13.978 +0000 UTC 5s}"
TRAC[2021-03-15T16:27:14-07:00] http://demo.robustperception.io:9090          api=QueryRange error="bad_data: exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)" query="sum by(cpu) (node_cpu_guest_seconds_total)" r="{2021-03-01 23:27:10 +0000 UTC 2021-03-15 23:27:13.978 +0000 UTC 5s}" took=374.414699ms value="<nil>" warnings="[]"
DEBU[2021-03-15T16:27:14-07:00] VectorSelector: node_cpu_guest_seconds_total 
DEBU[2021-03-15T16:27:14-07:00] http://demo.robustperception.io:9090          api=QueryRange query=node_cpu_guest_seconds_total r="{2021-03-01 23:27:10 +0000 UTC 2021-03-15 23:27:13.978 +0000 UTC 5s}"
TRAC[2021-03-15T16:27:14-07:00] http://demo.robustperception.io:9090          api=QueryRange error="bad_data: exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)" query=node_cpu_guest_seconds_total r="{2021-03-01 23:27:10 +0000 UTC 2021-03-15 23:27:13.978 +0000 UTC 5s}" took=161.697203ms value="<nil>" warnings="[]"
127.0.0.1 - - [15/Mar/2021 23:27:14] "GET /api/v1/query_range HTTP/1.1 200 87" 0.709924 query=avg_over_time%28%28sum+by+%28cpu%29+%28node_cpu_guest_seconds_total%29%29%5B1w%3A%5D%29&start=1615246033.978&end=1615850833.978&step=2419
```

Edit:
After debugging it seems like the interval value is getting passed as 5sec (from the evaluationInterval). 
Another observation is that the range for the downstream query is 14d instead of 7d.
`r="{2021-03-01 23:27:10 +0000 UTC 2021-03-15 23:27:13.978 +0000 UTC 5s}`
