### ISSUE TITLE
Promxy not triggering any alerts in the Alerts Tab

### ISSUE THREAD

**Issue by gr8Adakron** [jacksontj/promxy#412]
@jacksontj I am trying to configure Promxy with Alertmanager by adding basic rules to Promxy. The architecture I am dealing with is multi shard prometheus send the metric to Victoria Metric and then Promxy pulling from VM. 

Promxy is a single source to apply all the rules for alerting on and Alertmanager is also deploy is the same cluster.

The problem: I can see alerting rule appearing in dashboard, here

<img width="1404" alt="Screenshot 2021-03-30 at 3 53 45 PM" src="https://user-images.githubusercontent.com/16715364/112974474-23ec8580-9170-11eb-962d-b9d79c6eee8f.png">

And when I try to run the same query as that of alerting rule - I can see my condition is satisfied, here
<img width="1386" alt="Screenshot 2021-03-30 at 3 55 19 PM" src="https://user-images.githubusercontent.com/16715364/112974659-58604180-9170-11eb-9016-cced5da48aae.png">

So Ideally it should send an alert in the alerting tab then to Alertmanager configure in the same cluster, but promxy-> alert tabe doesnt show anything, here:
That is nothing in firing tab everything is in Inactive tab

any thought or solution will be very much appreciated!

Promxy mainfestation image: `quay.io/jacksontj/promxy:v0.0.67`

Promxy Config.yaml
```
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    source: staging

rule_files:
- "/etc/promxy/*rules.yaml"

# Alerting specifies settings related to the Alertmanager.
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager-svc.monitoring.svc.cluster.local:9093"

remote_write:
  - url: http://localhost:8083/receive


promxy:
  server_groups:
    - static_configs:
        - targets:
          - victoria-metrics.internal:8428
      # labels to be added to metrics retrieved from this server_group
      labels:
        sg: vm_v1_8428
      anti_affinity: 10s
      remote_read: false
      query_params:
        nocache: 1
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true

      relative_time_range:
        start: -3h
        end: -1h

```

This is what happening in the logs of Promxy container:

```
time="2021-03-30T12:04:04Z" level=debug msg="default job:request_latency_seconds:mean5m{job=\"myjob\"} > 0.5 *parser.BinaryExpr"
time="2021-03-30T12:04:04Z" level=debug msg="VectorSelector: job:request_latency_seconds:mean5m{job=\"myjob\"}"
time="2021-03-30T12:04:04Z" level=debug msg="http://victoria-metrics.internal:8428" api=Query query="job:request_latency_seconds:mean5m{job=\"myjob\"}" ts="2021-03-30 12:04:04.598 +0000 UTC"
time="2021-03-30T12:04:04Z" level=trace msg="http://victoria-metrics.internal:8428" api=Query error="<nil>" query="job:request_latency_seconds:mean5m{job=\"myjob\"}" took="13.75µs" ts="2021-03-30 12:04:04.598 +0000 UTC" value="<nil>" warnings="[]"
time="2021-03-30T12:04:04Z" level=debug msg="AggregateExpr sum by(instance) (rate(node_disk_written_bytes_total[2m])) sum"
time="2021-03-30T12:04:04Z" level=debug msg="http://victoria-metrics.internal:8428" api=Query query="sum by(instance) (rate(node_disk_written_bytes_total[2m]))" ts="2021-03-30 12:04:04.598 +0000 UTC"
time="2021-03-30T12:04:04Z" level=trace msg="http://victoria-metrics.internal:8428" api=Query error="<nil>" query="sum by(instance) (rate(node_disk_written_bytes_total[2m]))" took="16.49µs" ts="2021-03-30 12:04:04.598 +0000 UTC" value="<nil>" warnings="[]"
time="2021-03-30T12:04:04Z" level=debug msg="call rate(node_disk_written_bytes_total[2m]) vector"
time="2021-03-30T12:04:04Z" level=debug msg="http://victoria-metrics.internal:8428" api=Query query="rate(node_disk_written_bytes_total[2m])" ts="2021-03-30 12:04:04.598 +0000 UTC"
time="2021-03-30T12:04:04Z" level=trace msg="http://victoria-metrics.internal:8428" api=Query error="<nil>" query="rate(node_disk_written_bytes_total[2m])" took="11.258µs" ts="2021-03-30 12:04:04.598 +0000 UTC" value="<nil>" warnings="[]"


```
