### ISSUE TITLE
Data Inconsistency while channeling through Promxy

### ISSUE THREAD

**Issue by gr8Adakron** [jacksontj/promxy#413]
Hey I have setup Promxy with Victoria Metric by adding target of Victoria Metric and visualising in Grafana dashboard

The full setup is as follows:

Prometheus   &nbsp;&nbsp;&nbsp;&nbsp;-->   Victoria Metric  &nbsp;&nbsp;&nbsp;-->     Promxy. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->     Grafana 
(Australlia zone)      &nbsp;&nbsp;&nbsp;&nbsp;  (SouthEast Asia)   &nbsp;&nbsp;&nbsp; &nbsp;         (SouthEast Asia)          (SouthEast Asia)

The issue is as I am trying to get the same query on Prometheus and Promxy (to check consistency):

### The Prometheus dashboard:
![image](https://user-images.githubusercontent.com/16715364/113105174-ebf04b80-921e-11eb-916c-63093a46b19c.png)

### The Promxy dashboard:
![image](https://user-images.githubusercontent.com/16715364/113105237-00344880-921f-11eb-93aa-aad181df6dd0.png)

The other weird thing is the Prometheus dashboard has all data while Promxy  dashboard only shows data if we timestamp filter of **>= 1hours** Which is Bizzare to me!

For example as you can see, no data for 30minute graph - which is present on Prometheus dashboard, ideally it should be present here as well.

![image](https://user-images.githubusercontent.com/16715364/113105514-4a1d2e80-921f-11eb-934e-8e2892c774e8.png)

any help will be appreciated!

## Theres no issue with Victoria Metric

Only when the data channels through Promxy its getting inconsistent. 

For example: If I add Victoria Metric as the source in Grafana then the data is consistent among:
* Prometheus Dashboard. - **Consistent**
* Grafana dashboard via Victoria Metric as source.  - **Consistent**

While if I add Promxy as the source the same before >1 hours data issue occurs:
* Prometheus Dashboard. - **Inconsistent**
* Grafana dashboard via Promxy as source.  - **Inconsistent**

My Promxy configuration: image: `quay.io/jacksontj/promxy:v0.0.68`

```
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    source: staging

rule_files:
- "/etc/promxy/*rules.yaml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager-svc.monitoring.svc.cluster.local:9093"

remote_write:
  - url: http://localhost:8082/receive

promxy:
  server_groups:
    - static_configs:
        - targets:
          - victoria-metrics.staging.internal:8428
      labels:
        sg: vm_v1_8428
      anti_affinity: 10s
      remote_read: false
      query_params:
        nocache: 1
      # configures the protocol scheme used for requests. Defaults to http
      scheme: http
      # options for promxy's HTTP client when talking to hosts in server_groups
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
      relative_time_range:
        start: -3h
        end: -1h
```

Similarly if I call CURL request to Promxy for the query:
```
 curl -g 'http://127.0.0.1:9090/api/v1/query?query=max_over_time(container_cpu_usage_seconds_total{namespace="assignments"}[1h])'
```
I get this

![image](https://user-images.githubusercontent.com/16715364/113167071-fd5a4780-9260-11eb-9823-f634fe1fa339.png)

And After running same query on Prometheus it returns correct data.

This is very strange behavior

**Comment by gr8Adakron** [comment]
Promxy Manifestation:

```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promxy
  template:
    metadata:
      labels:
        app: promxy
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: promxy-config
        args:
        - "--config=/etc/promxy/config.yml"
        - "--web.enable-lifecycle"
        - "--log-level=trace"
        env:
          - name: ROLE
            value: "1"
        command:
        - "/bin/promxy"
        image:  quay.io/jacksontj/promxy:v0.0.68
        imagePullPolicy: Always
        name: promxy
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 8082
          name: web
        volumeMounts:
        - mountPath: "/etc/promxy/"
          name: promxy-config
          readOnly: true
      # container to reload configs on configmap change
      - args:
        - "--volume-dir=/etc/promxy"
        - "--webhook-url=http://localhost:8082/-/reload"
        image: jimmidyson/configmap-reload:v0.1
        name: promxy-server-configmap-reload
        volumeMounts:
        - mountPath: "/etc/promxy/"
          name: promxy-config
          readOnly: true
      volumes:
      - configMap:
          name: promxy-config
        name: promxy-config
```

**Comment by jacksontj** [comment]
I took a quick look and was unable to reproduce the behavior you are seeing. Maybe you'd be able to reproduce this with a shared datasource? Maybe with the base config:

``` yaml
promxy:
  server_groups:
    # as many additional server groups as you have
    - static_configs:
        - targets:
          - demo.robustperception.io:9090
      labels:
        sg: localhost_9091
      anti_affinity: 10s
```

I would also suggest looking into the `trace` log output as it might shed some light on it.
