### ISSUE TITLE
Getting StaleNaN during rules processing

### ISSUE THREAD

**Issue by dileepranganathan** [jacksontj/promxy#440]
**Issue**
I have configured to run some recording and alert rules in promxy which is exported using the promxy-remote-write-exporter. I am frequently encountering StaleNaN in the samples for metrics generated from these rules. The problem is that some of the Alerts are using these metrics which get triggered on StaleNaN. After some debugging I found that the StaleNaN is getting added from [rules/manager.go#650](https://github.com/jacksontj/promxy/blob/master/vendor/github.com/prometheus/prometheus/rules/manager.go#L650)  and the rule expression Query response itself did not have any NaN in samples. I copied these rules from the downstream prometheus server (v2.19.2) where this behavior is not occurring (or at-least the StaleNaNs are getting ignored somewhere). Is there a way to make StaleNaN samples not get exported by the promxy remote-write-exporter or ignore it? Not sure if this is expected behavior. What should be the best approach to handle StaleNaNs in recording/alert rules? @jacksontj appreciate your guidance on this issue.

 **Alerts/Rules config** 
```
groups:
  - name: critical-pod-test
    rules:
      - expr: |-
          ((rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",namespace="test"}[15m]) > 3 / 900) * on(pod) group_left(node) node_namespace_pod:kube_pod_info:{namespace="test"}) * on(node) group_left(nodename) (count by(node) ((time() - label_join(node_boot_time_seconds, "node", "-", "nodename")) / 60 > 20))
        record: cluster:pod_crashlooping
      - alert: PodCrashLooping
        expr: cluster:pod_crashlooping
        for: 10m
        labels:
          severity: critical
```

**Setup/Config**
```
##
## Regular prometheus configuration
##
global:
  evaluation_interval: 30s
  external_labels:
    source: promxy
# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  - "*rule"
# remote_write configuration is used by promxy as its local Appender, meaning all
# metrics promxy would "write" (not export) would be sent to this. Examples
# of this include: recording rules, metrics on alerting rules, etc.
remote_write:
  - url: http://localhost:8083/receive

##
### Promxy configuration
##
promxy:
  server_groups:
    - static_configs:
        - targets:
            - prometheus:9090
      labels:
        cluster: demo
      anti_affinity: 30s
      remote_read: false
      remote_read_path: api/v1/read
      scheme: http
      http_client:
        dial_timeout: 5s
        tls_config:
          insecure_skip_verify: true
      ignore_error: true
```
