### ISSUE TITLE
v0.0.71: unexpected error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sagor999** [jacksontj/promxy#451]
Hello @jacksontj 
Recently installed 0.0.71 from 0.0.70 version, and noticed this error that is returned from promxy about once or twice in 24 hours:
```
 {\"status\":\"error\",\"errorType\":\"execution\",\"error\":\"unexpected error: runtime error: invalid memory address or nil pointer dereference\"}"
```
This is coming from vmalert when it connects to promxy to run alert queries. Simply re-running the query doesn't cause an error. 
Here is a full output:
```
{"ts":"2021-07-23T09:02:18.789Z","level":"error","caller":"VictoriaMetrics/app/vmalert/group.go:256","msg":"group \"/rules/servers.rules\": rule \"UbuntuServerDown\": failed to execute: failed to execute query \"up{osfamily=\\\"debian\\\"} == 0 unless ((up{osfamily=\\\"debian\\\", cluster=\\\"ceph\\\"} == 0) or (up{osfamily=\\\"debian\\\", instance=~\\\"^btea.*\\\"} == 0) or (up{osfamily=\\\"debian\\\", snmp_module=\\\"idrac\\\"} == 0) or (up{osfamily=\\\"debian\\\", snmp_module=\\\"ibm-imm\\\"} == 0))\": unexpected response code 422 for http://promxy-ingress-service:8082/api/v1/query?query=up%7Bosfamily%3D%22debian%22%7D+%3D%3D+0+unless+%28%28up%7Bosfamily%3D%22debian%22%2C+cluster%3D%22ceph%22%7D+%3D%3D+0%29+or+%28up%7Bosfamily%3D%22debian%22%2C+instance%3D~%22%5Ebtea.%2A%22%7D+%3D%3D+0%29+or+%28up%7Bosfamily%3D%22debian%22%2C+snmp_module%3D%22idrac%22%7D+%3D%3D+0%29+or+%28up%7Bosfamily%3D%22debian%22%2C+snmp_module%3D%22ibm-imm%22%7D+%3D%3D+0%29%29&step=1m0s&time=1627030920. Response body {\"status\":\"error\",\"errorType\":\"execution\",\"error\":\"unexpected error: runtime error: invalid memory address or nil pointer dereference\"}"}                                
```

I looked at logs in promxy, but there were no errors reported by promxy itself. 

Could it be due to parallel execution that was added in 0.71 version? 

And thank you for maintaining and keep updating promxy!!

**Comment by jacksontj** [comment]
Do you happen to have a repro case (e.g. query and config)? A panic like this is definitely unexpected and is a bug.

**Comment by sagor999** [comment]
It seems to happen on these two rules:
```
up{osfamily="debian"} == 0 unless ((up{osfamily="debian", cluster="ceph"} == 0) or (up{osfamily="debian", instance=~"^btea.*"} == 0) or (up{osfamily="debian", snmp_module="idrac"} == 0) or (up{osfamily="debian", snmp_module="ibm-imm"} == 0))
```

```
          p4_pull_master_journal_sequence{server_services="edge-server"} - p4_pull_replica_journal_sequence_applied{server_services="edge-server"} > 2.5e+10
          or p4_pull_master_journal_number{server_services="edge-server"} - p4_pull_replica_journal_number_applied{server_services="edge-server"} > 0
          or rate(p4_pull_replica_time{server_services="edge-server"}[15m]) == 0
```
So a query with lots of "or" in it, which means it hits that new parallel execution path. 

Though running that query a 1000 times would maybe get you 1 repro. :( 
For example, it happened only 6 times since I reported this issue. (and we have a lot of alert rules that constantly bombard promxy).

As for config, here is what we use for each server in `server_groups`
```
    - static_configs:
        - targets:
            - victoria-metrics.example.com
      scheme: https
      labels:
        promxy: prometheus.example.com
      anti_affinity: 10s
      remote_read: false
      remote_read_path: api/v1/read
      path_prefix: /select/0/prometheus
      query_params:
        nocache: 1
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
      ignore_error: true
```
And we have 7 servers like this that promxy checks. 
Besides that, here is global portion:
```
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy
```

Another thing, promxy is running as 3 pods, and traffic is load balanced between them. Though that shouldn't matter I think, as whole query is being executed on one pod.

**Comment by jacksontj** [comment]
I have spent a bit of time attempting to reproduce and have been unsuccessful so far. I looked and I don't see an obvious nil exception in the parallel child execution; but again I can't repro the issue.

Maybe you can reproduce it with some version against the following config (since Its easy to replicate):

```yaml
promxy:
  server_groups:
    - static_configs:
      - targets:
        - demo.robustperception.io:9090
        - demo.robustperception.io:9090
      http_client:
        dial_timeout: 1s
```
