### ISSUE TITLE
Aggregation over BinaryExpression returns no data when metrics are in different ServerGroups

### ISSUE THREAD

**Issue by dileepranganathan** [jacksontj/promxy#456]
**Issue**
No data being returned when the query is of type Aggregation over a BinaryExpression with LHS and RHS metrics from different server groups. For eg:
```
sum by (node) (cpu_limit{node=~"worker.*"} and on(pod) (kube_pod_status_phase{phase="Running"} == 1))
```
In this case the whole query is sent downstream and does not return any data as the `cpu_limit` metric is in server group 1 and kube_pod_status_phase is in server group 2. When I remove the aggregation, the LHS and RHS are send to both downstream and finally combined in promxy as expected. Is there a way the aggregation can be applied in promxy after querying the binary expression?

**Setup/Config**
```
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy

promxy:
  server_groups:
    - static_configs:
        - targets:
            - prometheus1.myserver.com
      labels:
        cluster: sg1
      anti_affinity: 30s
      remote_read: false
      remote_read_path: api/v1/read
      scheme: https
      http_client:
        dial_timeout: 5s
        tls_config:
          insecure_skip_verify: true
      ignore_error: false
    - static_configs:
        - targets:
            - prometheus2.myserver.com
      labels:
        cluster: sg2
      anti_affinity: 30s
      remote_read: false
      remote_read_path: api/v1/read
      scheme: https
      http_client:
        dial_timeout: 5s
        tls_config:
          insecure_skip_verify: true
      ignore_error: false
```
**Logs**
```
DEBU[2021-09-02T21:41:17-07:00] AggregateExpr count(cpu_limit{namespace="test",node=~"worker.*"} and on(pod) (kube_pod_status_phase{namespace="test",phase="Running"} == 1)) count
DEBU[2021-09-02T21:41:17-07:00] http://prometheus1.myserver.com/api/v1/read  api=Query query="count(cpu_limit{namespace=\"test\",node=~\"worker.*\"} and on(pod) (kube_pod_status_phase{namespace=\"test\",phase=\"Running\"} == 1))" ts="2021-09-03 04:41:17.351 +0000 UTC"
DEBU[2021-09-02T21:41:17-07:00] http://prometheus2.myserver.com/api/v1/read  api=Query query="count(cpu_limit{namespace=\"test\",node=~\"worker.*\"} and on(pod) (kube_pod_status_phase{namespace=\"test\",phase=\"Running\"} == 1))" ts="2021-09-03 04:41:17.351 +0000 UTC"
TRAC[2021-09-02T21:41:17-07:00] http://prometheus1.myserver.com/api/v1/read  api=Query error="<nil>" query="count(cpu_limit{namespace=\"test\",node=~\"worker.*\"} and on(pod) (kube_pod_status_phase{namespace=\"test\",phase=\"Running\"} == 1))" took=28.419489ms ts="2021-09-03 04:41:17.351 +0000 UTC" value= warnings="[]"
TRAC[2021-09-02T21:41:17-07:00] http://prometheus2.myserver.com/api/v1/read  api=Query error="<nil>" query="count(cpu_limit{namespace=\"test\",node=~\"worker.*\"} and on(pod) (kube_pod_status_phase{namespace=\"test\",phase=\"Running\"} == 1))" took=29.140967ms ts="2021-09-03 04:41:17.351 +0000 UTC" value= warnings="[]"
127.0.0.1 - - [03/Sep/2021 04:41:17] "GET /api/v1/query HTTP/1.1 200 87" 0.030615 query=count%28cpu_limit%7Bnamespace%3D%22test%22%2Cnode%3D~%22worker.%2A%22%7D+and+on%28pod%29+%28kube_pod_status_phase%7Bnamespace%3D%22test%22%2Cphase%3D%22Running%22%7D+%3D%3D+1%29%29&
```
