### ISSUE TITLE
Empty result when using offset modifier in query

### ISSUE THREAD

**Issue by jstaffans** [jacksontj/promxy#466]
I'm using promxy 0.0.73 and the following minimal configuration:

```yml
global:
  evaluation_interval: 30s
  external_labels:
    source: promxy

promxy:
  server_groups:
    - static_configs:
        - targets:
          # downstream Prometheus is version 2.29.2
          - prometheus.local
      anti_affinity: 10s
```

A query like `count(node_exporter_build_info)` works, but if you introduce the [offset modifier](https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier) like `count(node_exporter_build_info offset 2h)` the result set is empty. 

Querying the Prometheus query UI directly works so the problem seems to be in Promxy.
