### ISSUE TITLE
Error when testing rule in Grafana

### ISSUE THREAD

**Issue by MikaelElkiaer** [jacksontj/promxy#477]
I am seeing the following error when trying to create an alert in Grafana - for a promxy data source:

`request handler error: Post "promxy:8082": unsupported protocol scheme "promxy"`

I am using a config that is pretty much your k8s example, which is attached below.
I am also using a [ServiceMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitor) in order to pick up the metrics.

```
apiVersion: v1
data:
  config.yaml: |
    ##
    ## Regular prometheus configuration
    ##
    global:
      evaluation_interval: 5s
      external_labels:
        source: promxy

    # remote_write configuration is used by promxy as its local Appender, meaning all
    # metrics promxy would "write" (not export) would be sent to this. Examples
    # of this include: recording rules, metrics on alerting rules, etc.
    remote_write:
      - url: http://localhost:8083/receive

    ##
    ### Promxy configuration
    ##
    promxy:
      server_groups:
      - static_configs:
        - targets:
          - 10.148.15.221:9090
        labels:
          cluster: as
        remote_read: true
        http_client:
          dial_timeout: 5s
      - static_configs:
        - targets:
          - 10.152.15.213:9090
        labels:
          cluster: aus
        remote_read: true
        http_client:
          dial_timeout: 5s
      - static_configs:
        - targets:
          - 10.164.0.60:9090
        labels:
          cluster: eu
        remote_read: true
        http_client:
          dial_timeout: 5s
      - static_configs:
        - targets:
          - 10.128.15.195:9090
        labels:
          cluster: us
        remote_read: true
        http_client:
          dial_timeout: 5s
      - static_configs:
        - targets:
          - 10.150.0.61:9090
        labels:
          cluster: us-e
        remote_read: true
        http_client:
          dial_timeout: 5s

kind: ConfigMap
metadata:
  name: promxy-config
  namespace: monitoring

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: promxy
  name: promxy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promxy
  template:
    metadata:
      labels:
        app: promxy
    spec:
      containers:
      - args:
        - "--config=/etc/promxy/config.yaml"
        - "--web.enable-lifecycle"
        - "--log-level=trace"
        env:
          - name: ROLE
            value: "1"
        command:
        - "/bin/promxy"
        image: quay.io/jacksontj/promxy:v0.0.75
        imagePullPolicy: Always
        name: promxy
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 8082
          name: web
        volumeMounts:
        - mountPath: "/etc/promxy/"
          name: promxy-config
          readOnly: true
      # container to reload configs on configmap change
      - args:
        - "--volume-dir=/etc/promxy"
        - "--webhook-url=http://localhost:8082/-/reload"
        image: jimmidyson/configmap-reload:v0.1
        name: promxy-server-configmap-reload
        volumeMounts:
        - mountPath: "/etc/promxy/"
          name: promxy-config
          readOnly: true
      volumes:
      - configMap:
          name: promxy-config
        name: promxy-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: promxy
  labels:
    app: promxy
spec:
  ports:
  - protocol: TCP
    name: web
    port: 8082
    targetPort: 8082
  selector:
    app: promxy
```
