### ISSUE TITLE
Error executing query: context deadline exceeded when backend error

### ISSUE THREAD

**Issue by hailong1004** [jacksontj/promxy#501]
my promxy.yaml configuration:

```
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy
promxy:
  server_groups:
    - static_configs:
        - targets:
          - myhost1
          - myhost2
      ignore_error: true
```

my start command line:

```
./promxy-v0.0.75-linux-amd64 \
  --config=promxy.yaml \
  --log-level=debug \
  --bind-addr=:9088 \
  --query.timeout=5s \
  --web.read-timeout=5s \
  --http.shutdown-timeout=5s \
  --rules.alert.resend-delay=5s \
  --rules.alert.for-grace-period=5s \
  --rules.alert.for-outage-tolerance=5s \
  --query.lookback-delta=5s

```

myhost2 
When the myhost2 vm service fails, but tcp port is open:

```
# telnet myhost2 80
Trying 2.3.4.5...
Connected to 2.3.4.5.
Escape character is '^]'.


# time curl -I http://myhost2/metrics
curl: (56) Recv failure: Connection reset by peer

real	2m50.354s
user	0m0.008s
sys	0m0.003s
```

promxy get error: Error executing query: context deadline exceeded
![image](https://user-images.githubusercontent.com/18435715/154939291-fb2d3125-d9b6-4aec-a3ee-30290c4c30bd.png)

But if port 80 of myhost2 is closed, promxy can directly ignore the data of myhost2. Is this a bug of promxy?
