### ISSUE TITLE
Promxy returns non-existent time series when using aggregate function.

### ISSUE THREAD

**Issue by tifling85** [jacksontj/promxy#513]
Problem reproduction.

We have one prometheus and one promxy that redirects requests to prometheus.

`/opt/promxy/bin/promxy  --config=/opt/promxy/config/config.yml --bind-addr=127.0.0.1:9091`

```
global:
  evaluation_interval: 5s
  external_labels:
    source: promxy

promxy:
  server_groups:
    - static_configs:
        - targets:
          - 192.168.199.215:9090
      anti_affinity: 10s
      query_params:
        nocache: 1
```
There is a metric that stopped coming at 10:00

![Screenshot from 2022-05-13 16-54-19](https://user-images.githubusercontent.com/54737545/168259634-a5c7c99a-4a73-41af-b64f-8f1e056a6c30.png)

When requesting this metric using an aggregation function through a promxy, 5 minutes of non-existent time series are returned.
Here the metric stopped coming at 10:05.

![Screenshot from 2022-05-13 16-56-08](https://user-images.githubusercontent.com/54737545/168259879-f28459dd-6da7-4d0f-8db3-cd08f7c6b58d.png)

When querying with an aggregating function directly in prometheus, the answer is correct.

curl requests:

without aggregate function:

```
curl 'http://localhost:9091/api/v1/query_range?query=smsc_scheduler_service_status\{service="sc-smsc-dlvrm"\}&start=2022-05-13T02:59:30.781Z&end=2022-05-13T03:06:00.781Z&step=30s'

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"smsc_scheduler_service_status","instance":"core-6.novalocal:","job":"sc-smsc-sched-health-exporter","service":"sc-smsc-dlvrm","service_type":"sc-smsc-dlvrm"},"values":[[1652410770.781,"1"],[1652410800.781,"1"]]}]}}
```

with aggregation function:
```
curl  'http://localhost:9091/api/v1/query_range?query=min(smsc_scheduler_service_status\{service="sc-smsc-dlvrm"\})&start=2022-05-13T02:59:30.781Z&end=2022-05-13T03:06:00.781Z&step=30s'

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1652410770.781,"1"],[1652410800.781,"1"],[1652410830.781,"1"],[1652410860.781,"1"],[1652410890.781,"1"],[1652410920.781,"1"],[1652410950.781,"1"],[1652410980.781,"1"],[1652411010.781,"1"],[1652411040.781,"1"],[1652411070.781,"1"],[1652411100.781,"1"]]}]}}
```

Thanks!
