### ISSUE TITLE
Inconsistent behaviour with functions like sum() or count()

### ISSUE THREAD

**Issue by hervenicol** [jacksontj/promxy#519]
Hi,
I am discovering promxy, and the tool looks fantastic but I have a few things I did not manage to setup correctly.
Here is for the first one!

## My setup
I have a sharded setup, where I have different clusters and each one has its dedicated prometheus.
I use promxy to access all of the data at once.
The prometheus servers are all part of a server_group, with `kubernetes_sd_configs` (all the prometheus are in a "management" kubernetes cluster)

## My problem

Now we have an inconsistent behaviour:
The number of `node_memory_MemTotal_bytes` per cluster is right:
* `count(node_memory_MemTotal_bytes) by (cluster_id)`:
```
{cluster_id="c3kj2"}  6
{cluster_id="gauss"}  16
```

But if I just want to count the total number of metrics I get the answer from one (random) cluster:
* `count(node_memory_MemTotal_bytes)`
gives sometimes `16`, sometimes `6`.

To have the total, I must do something like:
* `sum(count(node_memory_MemTotal_bytes) by (cluster_id))`
which gives a constant `22`.

I think my config is wrong for sharding, but this does not seem totally HA either, as it aggregates answers and even waits for down instances until timeout, which makes a big performance impact when one instance is down.

## My questions

* Is this behaviour on purpose? In which case we have to be extra careful with our requests, and double check all our grafana dashboards.
* Or is it something wrong with my config?

Thanks!

**Comment by SipSeb** [comment]
We stumbled upon this bug in the last days as well. In our case, we have a `dc` tag, which gets already filled in prometheus. When we don't do anything with this tag, the metrics are broken as described above. However, if we add the same tag with the same value again in promxy, those aggregation functions work as expected. 

From my point of view, this is not how it is expected. It can be worked around by specifying queries like this:
```
count(count(metric) ignore (dc))
```

But I don't think it's supposed to be done like that.

**Comment by SipSeb** [comment]
Found another workaround. If you set a label (or a set of labels) that is distinct for every target group, then the aggregation functions will work again.
```
     - static_configs:
         - targets:
             - host1:9091
             - host2:9091
       # labels to be added to metrics retrieved from this server_group
       labels:
         promsrc: dc1
         cluster: prod
[..]
     - static_configs:
         - targets:
             - host2:9091
             - host3:9091
       # labels to be added to metrics retrieved from this server_group
       labels:
         promsrc: dc2
         cluster: prod
```
