### ISSUE TITLE
Duplicate series error even when LHS has no data.

### ISSUE THREAD

**Issue by xujiaxj** [jacksontj/promxy#527]
When we have a `on(sth)` operator query, and the right side has duplicate series, promxy returns the "found duplicate series..." message even when the left side has on data. The correct behavior, as I expect, should instead be returning empty data, like Prometheus does.

This is super easy to reproduce. Setup a Prometheus in a way we have two jobs scraping the same endpoint, for example
```
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus-another'
    static_configs:
      - targets: ['localhost:9090']
```

This will produce two `up` series with the same `instance` label but different `job` label:
```
up{instance="localhost:9090", job="prometheus"} 1
up{instance="localhost:9090", job="prometheus-another"} 1
```

If you run this query `a * on(instance) up` in Prometheus, it returns empty result as `a` does not exist.
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/4541662/208202950-adcfc200-4f03-4d87-ba71-09bc921a25f7.png">

Now start a local promxy pointing to the local Prometheus, and run the same query through promxy (I am running Grafana UI). See that you now have "found duplicate series..." error.

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/4541662/208203127-46f3a6be-631a-47b6-8249-246b4fca3be1.png">
 
The same error happens if you run `a * on() up`. 

If you just run `a * up`, it does not error out, but returns empty data.
