### ISSUE TITLE
Promxy returns no rows when using long range

### ISSUE THREAD

**Issue by sc0rp10** [jacksontj/promxy#537]
Hi, trying to use promxy as a frontend in front of two VictoriaMetrics using a very simple config:

```yaml
promxy:
    server_groups:
        -
            consul_sd_configs:
                -
                    services:
                        - victoriametrics
```

CLI arguments are
```
--query.max-samples=150000000
--access-log-destination=none
--log-level=debug
```

Everything works like a charm except strange behavior when I use some long timerange. For example, I have a query `up == 1` - it works fine with any time ranges within my date retention. But when I querying `node_filesystem_size_bytes{hostname="foobar"}` I had no results for timeranges >= 43 days.
Response is 200 OK `{"status":"success","data":{"resultType":"matrix","result":[]}}` debug logs said nothing special.

Could anybody point me what's wrong?

Thanks!
