### ISSUE TITLE
write_relabel_configs don't drop metrics when [__name__] is filtered

### ISSUE THREAD

**Issue by xenofree** [jacksontj/promxy#547]
I try to not send metrics through remote_write

```
  - url: http:/xxxxx/api/v1/write
    write_relabel_configs:
    - source_labels: [__name__]
      regex: "unexistant"
      action: keep
```

This config should'nt send anything but i have this kind of logs

```
{"count":4000,"err":"server returned HTTP status 400 Bad Request: {\"error\":\"http: bad request\"}","fields.msg":"Error sending samples to remote storage","level":"warning","msg":"","queue":"1:http://xxxx/api/v1/write","time":"2023-03-08T12:58:35Z"}
```

and I see with tcpdump that packet are transmit.

I try this same config with a prometheus and, as it should be, there is nothing in log and nothing is transmited.

Do you know why there is a difference beetween promxy and prometheus ?
