### ISSUE TITLE
Promxy Crash v0.0.78

### ISSUE THREAD

**Issue by oOHenry** [jacksontj/promxy#579]
Yesterday I updated from v0.0.75 to v0.0.78, today a few hours ago I noticed the first crash of promxy

### Log:
```
promxy[3581835]: panic: runtime error: invalid memory address or nil pointer dereference
promxy[3581835]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4706c1]
promxy[3581835]: goroutine 29687 [running]:
promxy[3581835]: github.com/prometheus/prometheus/promql/parser.ExtractSelectors.func1({0x3909168?, 0xc001b6eab0?}, {0x10?, 0x2a46940?, 0x1?})
promxy[3581835]:         /home/tjackson/workspace/golang/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/parser/ast.go:373 +0x85
promxy[3581835]: github.com/prometheus/prometheus/promql/parser.inspector.Visit(0xc001793cd0, {0x3909168?, 0xc001b6eab0?}, {0xc001793d10?, 0x10?, 0x2a7b220?})
promxy[3581835]:         /home/tjackson/workspace/golang/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/parser/ast.go:383 +0x43
promxy[3581835]: github.com/prometheus/prometheus/promql/parser.Walk({0x391caf0, 0xc000054060}, {0x3900100, 0xc001793cd0}, 0xc001c0efa0, {0x3909168, 0xc001b6eab0}, {0xc001793d10, 0x1, 0x1}, ...)
promxy[3581835]:         /home/tjackson/workspace/golang/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/parser/ast.go:330 +0x209
promxy[3581835]: github.com/prometheus/prometheus/promql/parser.Walk.func1(0x1, {0x3909168, 0xc001b6eab0})
promxy[3581835]:         /home/tjackson/workspace/golang/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/parser/ast.go:344 +0x225
promxy[3581835]: created by github.com/prometheus/prometheus/promql/parser.Walk
promxy[3581835]:         /home/tjackson/workspace/golang/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/parser/ast.go:342 +0x405
systemd[1]: promxy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: promxy.service: Failed with result 'exit-code'.
systemd[1]: promxy.service: Consumed 38.875s CPU time.
```
unfortunately until now  I don't have a query or something to reproduce the crash.

Promxy Config:
```yaml
---
global:
  evaluation_interval: 1m
  external_labels:
    source: promxy
promxy:
  server_groups:
  - static_configs:
    - targets:
      - dc1-prometheus01.lan
      - dc2-prometheus01.lan
    scheme: https
    anti_affinity: 10s
    remote_read: false
    query_params:
      nocache: 1
    http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true

```
