### ISSUE TITLE
Latency increases when there are fewer requests

### ISSUE THREAD

**Issue by JuliaAlves** [jacksontj/promxy#591]
Hi, we are having some weird behavior on promxy and we are hoping you guys can help us figure it out.

## Context
We are running promxy pointing to several VictoriaMetrics clusters. 

**config:**
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
promxy:
  server_groups:
  - remote_read: false
    remote_read_path: api/v1/read
    http_client:
      dial_timeout: 10m0s
      follow_redirects: false
      enable_http2: false
    scheme: https
    labels: {}
    path_prefix: /select/<VM_ID>/prometheus
    query_params:
      nocache: "1"
    anti_affinity: 10s
    timeout: 10m0s
    ignore_error: true
    relative_time_range: null
    absolute_time_range: null
    label_filter: null
    … 
    # repeating for every vm cluster

tls_server_config:
  cert_file: ""
  key_file: ""
  client_auth_type: ""
  client_ca_file: ""
  cipher_suites: []
  curve_preferences: []
  min_version: 0
  max_version: 0
  prefer_server_cipher_suites: false
```

**version:**
v0.0.80

## Problem

We are seeing latency spikes on Grafana requests, but just when the usage is low (there are fewer requests being made). 

<img width="500" alt="Screenshot 2023-04-19 at 10 19 35" src="https://user-images.githubusercontent.com/20904535/233094283-3cbb1d91-657d-4f52-a0bf-11f7077620fb.png">

It seems cache related behavior, since there are less requests, there are more "cache misses". But looking at VictoriaMetrics, we can see the latency doesn't follow the same behavior. 

<img width="500" alt="Screenshot 2023-04-18 at 12 03 33" src="https://user-images.githubusercontent.com/20904535/233094451-2aebae8a-4e86-4388-a428-8deeccb756a8.png">

<img width="500" alt="Screenshot 2023-04-19 at 10 21 02" src="https://user-images.githubusercontent.com/20904535/233094429-2dbe43b3-c62d-409e-aae9-d58cfc1f7022.png">

This shows us that we problem is on promxy side. Taking a look at the prometheus engine metric, we can see that the duration of the `prepare_time` phase is following the pattern of higher latency. 

<img width="500" alt="Screenshot 2023-04-19 at 10 22 59" src="https://user-images.githubusercontent.com/20904535/233094509-66a86955-bf23-40bd-ac2c-45be4d32708e.png">

Compared with another prometheus (running similar queries), we don't see this difference in `prepare_time`.

<img width="500" alt="Screenshot 2023-04-19 at 10 27 16" src="https://user-images.githubusercontent.com/20904535/233094561-58b19f9d-5753-4889-b945-dc5bfddf9869.png">

Do you guys have any clue of what could possibly be going on? Is this a normal behavior? Promxy is caching something?
Or even, are there any debug tips?
