### ISSUE TITLE
Error when configuring Promxy to work with VictoriaMetrics that is behind Prometheus

### ISSUE THREAD

**Issue by hasanawad94** [jacksontj/promxy#604]
I have Prometheus scraping and writing to VictoriaMetrics cluster. I'm trying to configure Promxy to work with this setup.
I have deployed Promxy in kubernetes from the deploy folder:
```
---
apiVersion: v1
data:
  config.yaml: |
    ##
    ## Regular prometheus configuration
    ##
    #global:
    #  evaluation_interval: 5s
    #  external_labels:
    #    source: promxy

    # remote_write configuration is used by promxy as its local Appender, meaning all
    # metrics promxy would "write" (not export) would be sent to this. Examples
    # of this include: recording rules, metrics on alerting rules, etc.
    remote_write:
      - url: vm-insert.victoria.svc.cluster.local:8480/vminsert/insert/0/prometheus/api/v1/write

    ##
    ### Promxy configuration
    ##
    promxy:
      server_groups:
        - static_configs:
            - targets:
                - vm-select.victoria.svc.cluster.local:8481
          remote_read: false
          remote_read_path: ""
          path_prefix: "/vmselect/select/0/prometheus"
          query_params:
            nocache: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: promxy
  name: promxy
  namespace: victoria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promxy
  template:
    metadata:
      labels:
        app: promxy
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: promxy
      containers:
      - args:
        - "--config=/etc/promxy/config.yaml"
        - "--web.enable-lifecycle"
        - "--log-level=trace"
        env:
          - name: ROLE
            value: "1"
        command:
        - "/bin/promxy"
        image: registry/jacksontj/promxy:v0.0.77
        imagePullPolicy: Always
        name: promxy
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 8082
          name: web
        volumeMounts:
        - mountPath: "/etc/promxy/"
          name: promxy-config
          readOnly: true
      # container to reload configs on configmap change
      - args:
        - "--volume-dir=/etc/promxy"
        - "--webhook-url=http://localhost:8082/-/reload"
        image: registry/jimmidyson/configmap-reload:v0.1
        name: promxy-server-configmap-reload
        volumeMounts:
        - mountPath: "/etc/promxy/"
          name: promxy-config
          readOnly: true
      volumes:
      - configMap:
          name: promxy-config
        name: promxy-config
```
But I receive this error when trying to see metrics in the ui:
![image](https://github.com/jacksontj/promxy/assets/98394597/26717b22-b47b-4d31-acf0-7b2bd659221b)

**Comment by hasanawad94** [comment]
I have this config now and the metric is not showing up in ui: 
```
    ##
    ### Promxy configuration
    ##
    promxy:
      server_groups:
        - static_configs:
            - targets:
                - vm-cluster-vmselect.victoria.svc.cluster.local:8481
          remote_read: false
          labels: {}
          scheme: http
          absolute_time_range:
            start: '2023-06-01T01:00:00Z'
            end: '2023-07-06T01:00:00Z'
            truncate: true
          label_filter: null
          ignore_error: true
          remote_read_path: '/api/v1/query'
          path_prefix: '/vmselect/select/0/prometheus'
          query_params:
            nocache: 1

```

Promxy is giving this error when I try to query:

`msg="http://vm-cluster-vmselect.victoria.svc.cluster.local:8481/vmselect/select/0/prometheus" api=Query error="nil" query=http_requests_total took="22.866µs" ts="2023-07-06 09:09:42.669 +0000 UTC" value="<nil>" warnings="[]"`


I verified the url with curl and gotten success:
```
curl -XGET "http://vm-cluster-vmselect.victoria.svc.cluster.local:8481/vmselect/select/0/prometheus/api/v1/query?query=http_requests_total" |jq

{
  "status": "success",
  "isPartial": false,
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "http_requests_total",
          "container": "metrics-provider",
          "endpoint": "http",
          "instance": "192.168.251.47:8080",
          "job": "sample-app",
          "namespace": "victoria",
          "pod": "sample-app-64c54b8c68-pqp8j",
          "prometheus": "victoria/cpro-prometheus-resource",
          "prometheus_replica": "prometheus-cpro-prometheus-resource-0",
          "service": "sample-app"
        },
        "value": [
          1688635143,
          "2429"
        ]
      }
    ]
  }
}
```
