### ISSUE TITLE
promxy to prometheus "remote_read" calls using "query" / "query_range" instead

### ISSUE THREAD

**Issue by BertHartm** [jacksontj/promxy#631]
I've been trying to test out the remote_read functionality, but I'm seeing that promxy is not actually making the remote read calls, and is instead using the query / query_range calls when I run queries via the promxy UI.

I have the following promxy config:
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 30s
promxy:
  server_groups:
  - remote_read: true
    remote_read_path: api/v1/read
    http_client:
      dial_timeout: 200ms
      follow_redirects: false
      enable_http2: false
    scheme: http
    labels: {}
    path_prefix: ""
    query_params: {}
    anti_affinity: 10s
    ignore_error: false
    relative_time_range: null
    absolute_time_range: null
    label_filter: null
    static_configs:
    - targets:
      - localhost:9090
tls_server_config:
  cert_file: ""
  key_file: ""
  client_auth_type: ""
  client_ca_file: ""
  cipher_suites: []
  curve_preferences: []
  min_version: 0
  max_version: 0
  prefer_server_cipher_suites: false
```

most of that is default, but `remote_read: true` was explicitly set in my config file.

I'm running wireshark to see the actual request sent to prometheus from promxy, and it's a `POST /api/v1/query_range` instead of the expected `POST /api/v1/read`.

```
Frame 239: 313 bytes on wire (2504 bits), 313 bytes captured (2504 bits) on interface lo0, id 0
...
Hypertext Transfer Protocol
HTML Form URL Encoded: application/x-www-form-urlencoded
    Form item: "end" = "1700857449.92"
    Form item: "query" = "up"
    Form item: "start" = "1700853849.92"
    Form item: "step" = "14"
```

Additionally, the promxy metrics seem to support this with:
```
# HELP prometheus_remote_storage_read_request_duration_seconds Histogram of the latency for remote read requests.
# TYPE prometheus_remote_storage_read_request_duration_seconds histogram
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="0.005"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="0.01"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="0.025"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="0.05"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="0.1"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="0.25"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="0.5"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="1"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="2.5"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="5"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="10"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="25"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="60"} 0
prometheus_remote_storage_read_request_duration_seconds_bucket{remote_name="foo",url="http://localhost:9090/api/v1/read",le="+Inf"} 0
prometheus_remote_storage_read_request_duration_seconds_sum{remote_name="foo",url="http://localhost:9090/api/v1/read"} 0
prometheus_remote_storage_read_request_duration_seconds_count{remote_name="foo",url="http://localhost:9090/api/v1/read"} 0
# HELP prometheus_remote_storage_remote_read_queries The number of in-flight remote read queries.
# TYPE prometheus_remote_storage_remote_read_queries gauge
prometheus_remote_storage_remote_read_queries{remote_name="foo",url="http://localhost:9090/api/v1/read"} 0
```
...
```
# HELP server_group_request_duration_seconds Summary of calls to servergroup instances
# TYPE server_group_request_duration_seconds summary
server_group_request_duration_seconds_sum{call="query_range",host="localhost:9090",status="success"} 0.014273459
server_group_request_duration_seconds_count{call="query_range",host="localhost:9090",status="success"} 1
```
showing that it created the remote connection, but never called it and called query_range instead.

I'm building off master:
```
promxy, version  (branch: , revision: 300c73943dd83efb396f4aadb7f24cd4303a0155)
  build user:
  build date:
  go version:       go1.21.4
  platform:         darwin/arm64
  tags:             netgo,builtinassets
```
