### ISSUE TITLE
promxy did not get external_labels from server_groups

### ISSUE THREAD

**Issue by deniszh** [jacksontj/promxy#652]
Promxy do not retrieves any "external_labels" from server_groups, which breaks compatibility with Prometheus.
In our case we migrated to labels, but I can imagine use case where it can be tricky.

**Comment by jacksontj** [comment]
First off, thanks for reaching out!

I am a bit confused by the report/question here. Some of this is likely due to `external_labels` in prometheus being a bit of a confusing topic. From the [prometheus docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/):
```
  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
```

This means that these labels aren't returned in the metrics queries -- but rather when being sent out to external systems (e.g. alertmanager). This is especially murky since it indicates that it shows up in "remote storage" but not in the regular query interface (super confusing).

Promxy is passing the external labels config to the [prometheus rule manager](https://github.com/jacksontj/promxy/blob/master/cmd/promxy/main.go#L351) so these external labels are added to alerts fired to alertmanager; but that is the only current usage of these external labels.

In your usage; where are you expecting to see these external labels?

**Comment by deniszh** [comment]
Hi @jacksontj 
Thanks for your response!
Sorry for not providing more details, let me explain issue.
Assume setup like this:

```
--> Prometheus (frontend) --> Prometheus Backend A
               |
               +------------> Prometheus Backend B                       
```

If Prom A has config
```
external_labels:
      replica: a
      cluster: b
      role: c
```
and Prom B has config
```
external_labels:
      replica: x
      cluster: y
      role: z
```
and both of them have metric `metric1` (let's assume w/o labels for simplicity) then if we query Prometheus frontend for metric1 we'll get
```
metric1{replica: a, cluster: b, role: c}
metric1{replica: x, cluster: y, role: z}
```

Next step - let's replace Prometheus Frontend with Promxy, with following setup:
```
server_groups:
    - static_configs:
        - targets:
          - promA:9090
    - static_configs:
        - targets:
          - promB:9090
``` 

Then similar request for metric1 to promxy would return
```
metric1{}
```
(and it would be metric1 from PromA btw).

So, if you know external labels for PromA and PromB fix is obvious:
```
server_groups:
    - static_configs:
        - targets:
          - promA:9090
             labels:
                  replica: a
                  cluster: b
                  role: c
    - static_configs:
        - targets:
          - promB:9090
             labels:
                  replica: x
                  cluster: y
                  role: z
``` 

It's obviously restoring old behavior. So, it's bad for breaking compatibility (but IIRC promxy do not promise any) and I can imagine some issues only if external labels is dynamic and not easily obtainable in promxy - which is kinda theoretical.
So, maybe we can just mention behavior above near `labels` field in example config and call it a day.
