### ISSUE TITLE
422 Unprocessable Entity on random queries

### ISSUE THREAD

**Issue by paulojmdias** [jacksontj/promxy#687]
Hi,

I'm seeing some random HTTP 422 in some random queries that come from Grafana. I have done 20+ simultaneous curl requests, and randomly I see those HTTP 422. Even with debug logs enabled, I don't see anything wrong.

What can cause this ? Anything can be improved on the configuration?

<img width="2474" alt="image" src="https://github.com/user-attachments/assets/8619107a-ef3f-4db9-b240-93b3704f9ae0">

```yaml
promxy:
  server_groups:
  - http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
    http_headers:
      X-Scope-OrgID: org1|org2
    path_prefix: /prometheus
    remote_read: false
    scheme: https
    static_configs:
    - targets:
      - dns.domain.com:8080
```

On Grafana side I see HTTP 500, which is weird since I don't see it on Promxy logs.

![image](https://github.com/user-attachments/assets/ef56ef42-0aed-486d-9ac5-3384c1f32b14)
