### ISSUE TITLE
Unable to get remote_write to send custom HTTP headers

### ISSUE THREAD

**Issue by JohanLindvall** [jacksontj/promxy#694]
Using

```
remote_write:
  - url: http://mimir-nginx.monitoring-mimir.svc.cluster.local/api/v1/push
    headers:
      'X-Scope-OrgID': longterm
```

as a remote write configuration still sends metrics to the default Mimir tenant.

A brief look at the code shows that`Headers` parameter of the `RemoteWriteConfig` isn't used anywhere.

Is this expected?
