### ISSUE TITLE
Wrong query result from aggregation Operators

### ISSUE THREAD

**Issue by paulojmdias** [jacksontj/promxy#703]
I have the following setup with 3 server groups

```
promxy
  -> Grafana mimir dc1
      -> dc1
      -> google-us-dc1
      -> google-us-dc2
  -> Grafana mimir dc2
      -> dc2
      -> google-us-dc1
      -> google-us-dc2
  -> Grafana mimir dc3
      -> dc3
      -> google-eu-dc1
      -> google-eu-dc2
```

When we do the following query `count(up{label_key="label_value"}) by (region)` we have the following results:

```
{region="dc1"}                       342
{region="google-us-dc1"}    31
{region="google-us-dc2"}    31
{region="dc2"}                       341
{region="dc3"}                       30
{region="google-eu-dc1"}     25
{region="google-eu-dc2"}     24
{region="google-eu-dc3"}     29
{region="google-eu-dc4"}     36
{region="google-eu-dc5"}     29
```

If we remove the aggregator and do the query `count(up{label_key="label_value"})` I expect to have the value `918`, but the truth is promxy are returning the max value from the 3 server groups we have, which is `404` and in this case comes from the sum from the data which resides on `Grafana mimir dc1`

```
{region="dc1"}                       342
{region="google-us-dc1"}    31
{region="google-us-dc2"}    31
```

I also did a test, I added a dedicated label to each server group, named `__dc__`, and when we do the query `count(count(up{stack="persistence"}) without (__dc__))`, we have the desired value which is `918`.
However, let's go and do the expected query `count(up{stack="persistence"})`. We will have the value `980` since they are counting the values from `google-us-dc1` and `google-us-dc2` twice because when we add custom labels per server group, we are saying the data on each server group is unique, which is not the case.

Although we are using Mimir, in the end, is a Prometheus query API that we are using, so I don't feel it is related.

I already tried to debug in Promxy code, but I ran without ideas and I decided to open this issue. I'm open to contribute either way if I find something 🙌

**Comment by jacksontj** [comment]
Thanks for reaching out, lets jump into it!

> I have the following setup with 3 server groups

I believe there may be a typo in this example; as described this configuration has some overlapping DCs (`google-us-dc1` is in mimir dc1 and dc2). Given that the example below has eu-dc1..5 -- I'm assuming mimir dc2 was supposed to be eu? (since otherwise i don't see eu dc3,4,5).

> but the truth is promxy are returning the max value from the 3 server groups we have,

This sounds like maybe the servergroup configuration isn't quite right -- as the NodeReplacer (that does the max/rewrite) is done at the top-level. All of the servergroup merging is done lower down. So this *does* sound like an issue with the servergroup configuration rather than the aggregation rewrite in NodeReplacer.

> Although we are using Mimir, in the end, is a Prometheus query API that we are using, so I don't feel it is related.

This seems correct; this seems like an issue with the promxy servergroup config not quite matching your setup.

> We are not overriding the prefer_max option and we are using the version v0.0.91.

If we are running into `prefer_max` we are definitely hitting a servergroup configuration issue. The `prefer_max` is intended to handle merging of data within a servergroup (defined as a set of API endpoints that "have the same data").

>  I ran without ideas and I decided to open this issue

I'd be happy to give a hand here! Could you provide your promxy config? Or at least the servergroup configuration. As well as re-iterating the downstreams, their data, and desired merging behavior. I think from there we'll be able to make some progress :)

**Comment by paulojmdias** [comment]
@jacksontj here is the promxy configuration for us to kick off this analysis :D 

```yaml
promxy:
  server_groups:
  - http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
    http_headers:
      X-Scope-OrgID: dc1|google-us-dc1|google-us-dc2
    path_prefix: /prometheus
    remote_read: false
    scheme: https
    static_configs:
    - targets:
      - mimir.dc1.local:8080
  - http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
    http_headers:
      X-Scope-OrgID: dc2|google-us-dc1|google-us-dc2
    path_prefix: /prometheus
    remote_read: false
    scheme: https
    static_configs:
    - targets:
      - mimir.dc2.local:8080
  - http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
    http_headers:
      X-Scope-OrgID: dc3|google-eu-dc1|google-eu-dc2
    path_prefix: /prometheus
    remote_read: false
    scheme: https
    static_configs:
    - targets:
      - mimir.dc3.local:8080
```

**Comment by mut3** [comment]
👋  I work with @paulojmdias and though I have less experience with this stack, I think can answer some of the questions.

I have tried in my message to be clear about when I am referring to a server group and when I am referring to a datacenter (DC). In the example queries, we use `region` as a label for the individual datacenters.

> I believe there may be a typo in this example; as described this configuration has some overlapping DCs (`google-us-dc1` is in mimir dc1 and dc2). Given that the example below has eu-dc1..5 -- I'm assuming mimir dc2 was supposed to be eu? (since otherwise i don't see eu dc3,4,5).

Mimir dc3 server group is our EU. group, I believe eu-dc3/4/5 were omitted for simplicity in the original post, it could have been:

```
promxy
  ...
  -> Grafana mimir dc3
      -> dc3
      -> google-eu-dc1
      -> google-eu-dc2
      -> google-eu-dc3
      -> google-eu-dc4
      -> google-eu-dc5
 ```

(The same can be assumed for the servergroup config Paulo shared yesterday, dc3 server group `X-Scope-OrgID` headers include all google-eu DCs)

> I'd be happy to give a hand here! Could you provide your promxy config? Or at least the servergroup configuration. As well as re-iterating the downstreams, their data, and desired merging behavior. I think from there we'll be able to make some progress :)

Mimir dc1 server group and mimir dc2 server group are both in NA and separately contain metrics from themselves. Our cloud metrics `google-us-dc1`/`google-us-dc2` send to both for redundancy. We can assume that the series with `region=~"google-us-dc[12]"`  in mimir dc1 server group match those in mimir dc2 server group during normal operation. For all other DCs, there is only one copy of their data between the three server groups.

Our expected behavior when making a query such as `count(up{label_key="label_value"})` is that series from `google-us-dc1` and `google-us-dc2` are deduplicated and all other DCs are retained. See the original post for actual behavior.

**Comment by jacksontj** [comment]
> Our expected behavior when making a query such as count(up{label_key="label_value"}) is that series from google-us-dc1 and google-us-dc2 are deduplicated and all other DCs are retained.

This makes a LOT of sense. So to make sure I'm understanding this correctly you effectively have 7 "regions":

    - dc1
    - google-us-dc1
    - google-us-dc2
    - dc2
    - dc3
    - google-eu-dc1
    - google-eu-dc2


And your mimir dc1 has duplicated data for the "google-us" regions as DC2 -- but also includes unique data (dc1 vs dc2).


So to reproduce this I have created some local stub endpoints with the following series

    /dc1:
        - prometheus_build_info{region="dc1"}           // Unique data
        - prometheus_build_info{region="gcp-us-1"}      // Duplicated data
    /dc2:
        - prometheus_build_info{region="dc2"}           // Unique data
        - prometheus_build_info{region="gcp-us-1"}      // Duplicated data
    /dc3:
        - prometheus_build_info{region="dc3"}           // Unique data
        - prometheus_build_info{region="gcp-eu-1"}      // Unique data

When I do a query for `prometheus_build_info` I get seemingly the correct results:

```
prometheus_build_info{region="dc1"}	1
prometheus_build_info{region="gcp-us-1"}	1
prometheus_build_info{region="dc2"}	1
prometheus_build_info{region="dc3"}	1
prometheus_build_info{region="gcp-eu-1"}	1
```

And when I do a `count(prometheus_build_info) by (region)` I get a similarly correct-looking result:

```
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "region": "dc1"
        },
        "value": [
          1738881180.036,
          "1"
        ]
      },
      {
        "metric": {
          "region": "gcp-us-1"
        },
        "value": [
          1738881180.036,
          "1"
        ]
      },
      {
        "metric": {
          "region": "dc2"
        },
        "value": [
          1738881180.036,
          "1"
        ]
      },
      {
        "metric": {
          "region": "dc3"
        },
        "value": [
          1738881180.036,
          "1"
        ]
      },
      {
        "metric": {
          "region": "gcp-eu-1"
        },
        "value": [
          1738881180.036,
          "1"
        ]
      }
    ]
  }
}```


So assuming my understanding is correct; and my test-data here is correct-- I think I know the issue. The data deduplication in promxy is done based on the labels associated with a timeseries. At its simplest form a series with the same labels is considered the same as another. So if there are 2 results across servergroups for `foo{a="1"}` -- they will be combined. Now if there is *any* deviation in labels then they will *not* be combined. So my theory here is that there is some external_label being set on mimir that specifies which `dc` it is coming from. So although a series in `google-us-dc1` might be `foo{region="google-us-dc1"}` mimir *could* be adding something some labels to make it `foo{region="google-us-dc1", dc="dc1"}` -- which would make it appear as a different series from the dc2 mimir.

So to confirm/deny this I'd suggest looking at the series results that promxy is getting. To simplify this a bit you can maybe filter to a specific region (since that seems to reduce most of the series) and see what promxy sees (either doing the CURL yourself; or looking at the trace logs).


If you want to play around with my toy local repro you can do so by un-taring [data.tar.gz](https://github.com/user-attachments/files/18698522/data.tar.gz),  in that directory running `python3 -m http.server 8000`, use the below promxy config, and query promxy with something like `http://localhost:8082/promxy/api/v1/query?query=count(prometheus_build_info)%20by%20(region)&time=1738881180.036`:

promxy config:

```yaml
##
promxy:
  server_groups:
    - static_configs:
        - targets:
          - localhost:8000
      path_prefix: /dc1
    - static_configs:
        - targets:
          - localhost:8000
      path_prefix: /dc2
    - static_configs:
        - targets:
          - localhost:8000
      path_prefix: /dc3
```

**Comment by mut3** [comment]
Your understanding of our regions is correct :)


> The data deduplication in promxy is done based on the labels associated with a timeseries. At its simplest form a series with the same labels is considered the same as another. So if there are 2 results across servergroups for `foo{a="1"}` -- they will be combined. Now if there is *any* deviation in labels then they will *not* be combined. So my theory here is that there is some external_label being set on mimir that specifies which `dc` it is coming from. So although a series in `google-us-dc1` might be `foo{region="google-us-dc1"}` mimir *could* be adding something some labels to make it `foo{region="google-us-dc1", dc="dc1"}` -- which would make it appear as a different series from the dc2 mimir.


I think we have the same understanding that this is how promxy should work, and totally understand that promxy will not deduplicate series with differing labels. In general promxy is correctly deduplicating our `google-us-dc[12]` data. The unexpected result we are seeing is that the unique data seems to be getting combined when it should not if the query is not aggregated by some label.

```
count(up{label="foobar"}) by (region)


{region="dc1"}                       383
{region="google-us-dc1"}    31
{region="google-us-dc2"}    31
{region="dc2"}                       403
{region="dc3"}                       34
{region="google-eu-dc1"}     25
{region="google-eu-dc2"}     24
{region="google-eu-dc3"}     29
{region="google-eu-dc4"}     36
{region="google-eu-dc5"}     29
```

This result is correct, properly deduplicated, and based on this, we would expect `count(up{label="foobar"})` to give 1025. We can get that value by summing the previous query results.

```
sum(count(up{stack="persistence"}) by (region))

1025
```

But, the unexpected result is that `count(up{label="foobar"})` does not give 1025

```
count(up{label="foobar"})

445
```

What I am guessing is happening based on this number is that promxy is first deduplicating data from the us google dcs, then for some reason, giving the `max()` of the result from the three (or just choosing the first server group's result).

Perhaps this is _because_ we are not aggregating? So promxy is getting three different unlabeled vectors back from the three server groups? 


```
promxy
  -> Grafana mimir dc1: 445
      -> dc1: 383
      -> google-us-dc1: 31
      -> google-us-dc2: 31
  -> Grafana mimir dc2: 467 (403 if duplicated google data removed)
      -> dc2: 403
      -> google-us-dc1: 31
      -> google-us-dc2: 31
  -> Grafana mimir dc3: 177
      -> dc3: 34
      -> google-eu-dc1: 25
      -> google-eu-dc2: 24
      -> google-eu-dc3: 29
      -> google-eu-dc4: 36
      -> google-eu-dc5: 29
```

-----


Thank you very much for providing a tiny test bed, I'll pull your tarball and try to replicate this behavior in it so we can better understand this issue

**Comment by jacksontj** [comment]
> But, the unexpected result is that count(up{label="foobar"}) does not give 1025

Given that it is less; my assumption here is that some of those series end up having the same labels when promxy sees them (in the API response). The logic around sum/max/etc. seems *unlikely* to be the problem.

> Thank you very much for providing a tiny test bed

You are more than welcome; also if its easier feel free to upload the trace logs of your query example from above -- from that we'll be able to easily see what queries/results each servergroup is getting. With that it should be easy to see what is happening.

**Comment by mut3** [comment]
Okay, to see if promxy was actually choosing `max()` across the server groups or just choosing the first server group I chose a different label and value pair that would return a higher count in our `dc3` server group.

```
count(up{different_label="bazbar"}) by (region)


{region="dc1"                        100
{region="google-us-dc1"}    31
{region="google-us-dc2"}    31
{region="dc2"}                       0
{region="dc3"}                       47
{region="google-eu-dc1"}     98
{region="google-eu-dc2"}     65
{region="google-eu-dc3"}     94
{region="google-eu-dc4"}     36
{region="google-eu-dc5"}     61
```

```
sum(count(up{different_label="bazbar"}) by (region))

563
```

Based on this, server group totals are

```
mimir dc1: 162
mimir dc2: 62
mimir dc3: 401
```

So we can infer from

```
count(up{different_label="bazbar"})

162
```

that promxy is picking the first server group when it has three different unlabelled vectors to choose from.

**Comment by jacksontj** [comment]
> that promxy is picking the first server group when it has three different unlabelled vectors to choose from.

This sounds like there is some label issue where it is seeing the results as "the same" (meaning it just picks one as it believes them to be the same).

Are you able to reproduce this on that small test set? Or able to provide the trace logs?

**Comment by mut3** [comment]
Working on doing this in the test set now, might take me some time though

**Comment by jacksontj** [comment]
FYI, I was re-reviewing the earlier convos -- given that your PR includes changes in the series merging it is most likely a scenario where promxy is getting multiple series with the same labels in response (so its merging instead of aggregating).

**Comment by mut3** [comment]
> it is most likely a scenario where promxy is getting multiple series with the same labels in response

I believe this is the case, a simple aggregation like `count()` is just returning a number with no labels.

**Comment by jacksontj** [comment]
As I'm thinking about this more -- I think this is actually somewhat related to https://github.com/jacksontj/promxy/issues/698.

So here is what I think is happening:
- query like `count(foo)` is sent to each servergroup
- each servergroup returns `{} NUMBER` -- which has no label differentiation
- promxy is then picking one -- as it believes the data is all the same

Normally this is a non-issue because users *generally* have either (1) different labels in the response or (2) `labels` set at the servergroup level. In your case we can't simply set `labels` because there is data overlap.

To attempt to clarify my rambling there; your current config has 3 servergroups -- but in reality there is quite a bit of overlap. To test this theory we could split them each into their own servergroup to avoid the issue like the following:

```
promxy:
  server_groups:
  - http_headers:
      X-Scope-OrgID: dc1
    path_prefix: /prometheus
    scheme: https
    static_configs:
    - targets:
      - mimir.dc1.local:8080
    labels:
      dc: dc1
  - http_headers:
      X-Scope-OrgID: google-us-dc1
    path_prefix: /prometheus
    scheme: https
    static_configs:
    - targets:
      - mimir.dc1.local:8080
      - mimir.dc2.local:8080
    labels:
      dc: google-us-dc1
  - http_headers:
      X-Scope-OrgID: google-us-dc2
    path_prefix: /prometheus
    scheme: https
    static_configs:
    - targets:
      - mimir.dc1.local:8080
      - mimir.dc2.local:8080
    labels:
      dc: google-us-dc2
  - http_headers:
      X-Scope-OrgID: dc2
    path_prefix: /prometheus
    scheme: https
    static_configs:
    - targets:
      - mimir.dc2.local:8080
    labels:
      dc: dc2
  - http_headers:
      X-Scope-OrgID: dc3
    path_prefix: /prometheus
    scheme: https
    static_configs:
    - targets:
      - mimir.dc3.local:8080
    labels:
      dc: dc3
  - http_headers:
      X-Scope-OrgID: google-eu-dc1
    path_prefix: /prometheus
    scheme: https
    static_configs:
    - targets:
      - mimir.dc3.local:8080
    labels:
      dc: google-eu-dc1
  - http_headers:
      X-Scope-OrgID: google-eu-dc1
    path_prefix: /prometheus
    scheme: https
    static_configs:
    - targets:
      - mimir.dc3.local:8080
    labels:
      dc: google-eu-dc2
```

This feels a bit verbose -- but splits up the servergroups so that they are grouped by the `dc` which I *believe* will fix your merge issue. Assuming it does we can think about easier ways to describe this multi-tenant downstream.

**Comment by mut3** [comment]
I totally agree with your summary of what is happening. We may be able to test splitting up our promxy config like that and if we do we will get back to you.

**Comment by paulojmdias** [comment]
> As I'm thinking about this more -- I think this is actually somewhat related to [#698](https://github.com/jacksontj/promxy/issues/698).
> 
> So here is what I think is happening:
> 
> * query like `count(foo)` is sent to each servergroup
> * each servergroup returns `{} NUMBER` -- which has no label differentiation
> * promxy is then picking one -- as it believes the data is all the same
> 
> Normally this is a non-issue because users _generally_ have either (1) different labels in the response or (2) `labels` set at the servergroup level. In your case we can't simply set `labels` because there is data overlap.
> 
> To attempt to clarify my rambling there; your current config has 3 servergroups -- but in reality there is quite a bit of overlap. To test this theory we could split them each into their own servergroup to avoid the issue like the following:
> 
> ```
> promxy:
>   server_groups:
>   # dc1
>   - http_headers:
>       X-Scope-OrgID: dc1
>     path_prefix: /prometheus
>     scheme: https
>     static_configs:
>     - targets:
>       - mimir.dc1.local:8080
>     labels:
>       dc: dc1
>   # google-us-dc1
>   - http_headers:
>       X-Scope-OrgID: google-us-dc1
>     path_prefix: /prometheus
>     scheme: https
>     static_configs:
>     - targets:
>       - mimir.dc1.local:8080
>       - mimir.dc2.local:8080
>     labels:
>       dc: google-us-dc1
>   # google-us-dc2
>   - http_headers:
>       X-Scope-OrgID: google-us-dc2
>     path_prefix: /prometheus
>     scheme: https
>     static_configs:
>     - targets:
>       - mimir.dc1.local:8080
>       - mimir.dc2.local:8080
>     labels:
>       dc: google-us-dc2
>   # dc2
>   - http_headers:
>       X-Scope-OrgID: dc2
>     path_prefix: /prometheus
>     scheme: https
>     static_configs:
>     - targets:
>       - mimir.dc2.local:8080
>     labels:
>       dc: dc2
>   # dc3
>   - http_headers:
>       X-Scope-OrgID: dc3
>     path_prefix: /prometheus
>     scheme: https
>     static_configs:
>     - targets:
>       - mimir.dc3.local:8080
>     labels:
>       dc: dc3
>   # google-eu-dc1
>   - http_headers:
>       X-Scope-OrgID: google-eu-dc1
>     path_prefix: /prometheus
>     scheme: https
>     static_configs:
>     - targets:
>       - mimir.dc3.local:8080
>     labels:
>       dc: google-eu-dc1
>   # google-eu-dc2
>   - http_headers:
>       X-Scope-OrgID: google-eu-dc2
>     path_prefix: /prometheus
>     scheme: https
>     static_configs:
>     - targets:
>       - mimir.dc3.local:8080
>     labels:
>       dc: google-eu-dc2
> ```
> 
> This feels a bit verbose -- but splits up the servergroups so that they are grouped by the `dc` which I _believe_ will fix your merge issue. Assuming it does we can think about easier ways to describe this multi-tenant downstream.

@jacksontj your test suggestion makes it work. I also tested in the following way and also works as expected:

```yaml
promxy:
  server_groups:
  - http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
    http_headers:
      X-Scope-OrgID: dc1|google-us-dc1|google-us-dc2
    path_prefix: /prometheus
    remote_read: false
    scheme: https
    static_configs:
    - targets:
      - mimir.dc1.local:8080
    labels:
      dc: dc1
  - http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
    http_headers:
      X-Scope-OrgID: dc2|google-us-dc1|google-us-dc2
    path_prefix: /prometheus
    remote_read: false
    scheme: https
    static_configs:
    - targets:
      - mimir.dc2.local:8080
   labels:
      dc: dc2
  - http_client:
      dial_timeout: 1s
      tls_config:
        insecure_skip_verify: true
    http_headers:
      X-Scope-OrgID: dc3|google-eu-dc1|google-eu-dc2
    path_prefix: /prometheus
    remote_read: false
    scheme: https
    static_configs:
    - targets:
      - mimir.dc3.local:8080
```
