### ISSUE TITLE
Empty result when doing +1, panic when using scalar.

### ISSUE THREAD

**Issue by ml-aribezzi** [jacksontj/promxy#707]
I am using Promxy, Docker image: quay.io/jacksontj/promxy:v0.0.91 .
This is my config:
```
global:
  evaluation_interval: 30s
  external_labels:
    source: promxy
promxy:
  server_groups:
  - http_client:
      dial_timeout: 5s
      tls_config:
        insecure_skip_verify: true
    ignore_error: true
    labels:
      lumen: prometheus-observability-neo
    metrics_relabel_configs:
    - action: labeldrop
      source_label: prometheus_replica
    static_configs:
    - targets:
      - prometheus-lumen-promstack-primary-prometheus-0.prometheus-operated:9090
      - prometheus-lumen-promstack-primary-prometheus-1.prometheus-operated:9090
      - prometheus-lumen-promstack-primary-prometheus-2.prometheus-operated:9090
  - http_client:
      dial_timeout: 5s
    ignore_error: true
    labels:
      lumen: prometheus-argocd
    metrics_relabel_configs:
    - action: labeldrop
      source_label: prometheus_replica
    scheme: https
    static_configs:
    - targets:
      - one.prometheus-argocd.mycompany.io
      - two.prometheus-argocd.mycompany.io
      - three.prometheus-argocd.mycompany.io
  - http_client:
      dial_timeout: 5s
    ignore_error: true
    labels:
      lumen: prometheus-gitlab
    metrics_relabel_configs:
    - action: labeldrop
      source_label: prometheus_replica
    scheme: https
    static_configs:
    - targets:
      - one.prometheus-gitlab.mycompany.io
      - two.prometheus-gitlab.mycompany.io
      - three.prometheus-gitlab.mycompany.io
  - http_client:
      dial_timeout: 5s
    ignore_error: true
    labels:
      lumen: prometheus-harbor
    metrics_relabel_configs:
    - action: labeldrop
      source_label: prometheus_replica
    scheme: https
    static_configs:
    - targets:
      - one.prometheus-harbor.mycompany.io
      - two.prometheus-harbor.mycompany.io
      - three.prometheus-harbor.mycompany.io
  - http_client:
      dial_timeout: 5s
    ignore_error: true
    labels:
      lumen: prometheus-vault
    metrics_relabel_configs:
    - action: labeldrop
      source_label: prometheus_replica
    scheme: https
    static_configs:
    - targets:
      - one.prometheus-vault.mycompany.io
      - two.prometheus-vault.mycompany.io
      - three.prometheus-vault.mycompany.io
  - http_client:
      dial_timeout: 5s
    ignore_error: true
    labels:
      lumen: prometheus-gitlab-runners
    metrics_relabel_configs:
    - action: labeldrop
      source_label: prometheus_replica
    scheme: https
    static_configs:
    - targets:
      - one.prometheus-gitlab-runners.mycompany.io
      - two.prometheus-gitlab-runners.mycompany.io
      - three.prometheus-gitlab-runners.mycompany.io
rule_files:
- '*rule'
```

I have an issue, and found one more trying to solve it:
In Promxy, running  `vault_core_unsealed`  works and I get the following time series back:
`lumen_vault_primary_core_unsealed{app_kubernetes_io_instance="ml-vault-pr-vault-enterprise-primary", app_kubernetes_io_name="vault", cluster="Vault Enterprise Production Platform", container="vault", endpoint="http", helm_sh_chart="vault-0.28.1", instance="someip:8200", job="vault-ent-primary-active", lumen="prometheus-vault", namespace="vault", pod="somepod", service="vault-ent-primary-active", vault_active="true"}` with value 1.

If I run `lumen_vault_primary_core_unsealed + 1` I get an empty result instead. I get "2" when running this on Prometheus directly.
I then thought that I could use scalar(lumen_vault_primary_core_unsealed), but that threw an exception:
```
http://localhost:8082/api/v1/query?query=scalar%28lumen_vault_primary_core_unsealed%29&time=1738322950.435
Exception:
Error running handler: goroutine 270456 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/jacksontj/promxy/pkg/logging.(*ApacheLoggingHandler).runHandler.func1()
	/go/src/github.com/jacksontj/promxy/pkg/logging/logging.go:139 +0x33
panic({0x2a24240?, 0xc0019f4720?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/prometheus/prometheus/promql.(*evaluator).recover(0xc00164f620, 0xc001d26500, 0xc001d264f0)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:1004 +0x21e
panic({0x2728b20?, 0x39b4140?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/jacksontj/promxy/pkg/promclient.(*SeriesIterator).Labels(0x39e1820?)
	/go/src/github.com/jacksontj/promxy/pkg/promclient/iterators.go:129 +0x325
github.com/jacksontj/promxy/pkg/proxyquerier.(*Series).Labels(0x39e1820?)
	/go/src/github.com/jacksontj/promxy/pkg/proxyquerier/series.go:17 +0x16
github.com/prometheus/prometheus/promql.(*evaluator).eval(0xc00164f620, {0x39e15b8?, 0xc001516360?})
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:1597 +0x1ec2
github.com/prometheus/prometheus/promql.(*evaluator).rangeEval(0xc00164f620, 0x0, 0xc001d26270, {0xc00173c080, 0x1, 0x0?})
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:1080 +0x1ff
github.com/prometheus/prometheus/promql.(*evaluator).eval(0xc00164f620, {0x39e1708?, 0xc0019ba510?})
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:1365 +0x28ae
github.com/prometheus/prometheus/promql.(*evaluator).Eval(0x194bc1f3923?, {0x39e1708?, 0xc0019ba510?})
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:1011 +0x93
github.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc000526900, {0x39e1270, 0xc0019ba7b0}, 0xc0003ac000, 0xc000d9a0a0)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:646 +0x4ee
github.com/prometheus/prometheus/promql.(*Engine).exec(0xc000526900, {0x39e1270, 0xc0019ba7b0}, 0xc0003ac000)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:593 +0x4bb
github.com/prometheus/prometheus/promql.(*query).Exec(0xc0003ac000, {0x39e1270, 0xc0019ba600})
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/promql/engine.go:197 +0x1ee
github.com/prometheus/prometheus/web/api/v1.(*API).query(0xc0001be500, 0xc00154c300)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:412 +0x67e
github.com/prometheus/prometheus/web/api/v1.(*API).Register.(*API).Register.func2.func3(0x39d31a0?)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:313 +0x109
github.com/prometheus/prometheus/web/api/v1.(*API).Register.func1.1({0x39d31a0, 0xc000d9c000}, 0x7df024732538?)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:288 +0x74
net/http.HandlerFunc.ServeHTTP(0x7df024732538?, {0x39d31a0?, 0xc000d9c000?}, 0x410645?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP({{0x39b67a0?, 0xc000cbf1a0?}}, {0x7df024732538?, 0xc0019ba480?}, 0xc000f59180?)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/util/httputil/compression.go:90 +0x63
github.com/prometheus/prometheus/web.(*Handler).testReady-fm.(*Handler).testReady.func1({0x7df024732538, 0xc0019ba480}, 0x7df024732500?)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/web.go:542 +0x53
net/http.HandlerFunc.ServeHTTP(0x7df024732538?, {0x7df024732538?, 0xc0019ba480?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1({0x7df024732538?, 0xc0019ba3f0?}, 0xc00154c300)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:276 +0xca
net/http.HandlerFunc.ServeHTTP(0xffffffffffffffff?, {0x7df024732538?, 0xc0019ba3f0?}, 0xc0016a17a0?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x7df024732538, 0xc0019ba3f0}, 0xc00154c300)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:89 +0xc2
net/http.HandlerFunc.ServeHTTP(0x39d2540?, {0x7df024732538?, 0xc0019ba3f0?}, 0x2d2d700?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x39d2540?, 0xc001588120?}, 0xc00154c300)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:127 +0xb6
github.com/prometheus/prometheus/web.New.setPathWithPrefix.func17.1({0x39d2540, 0xc001588120}, 0xc00154c200)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/web.go:804 +0xb3
github.com/prometheus/common/route.(*Router).handle.func1({0x39d2540, 0xc001588120}, 0xc00154c100, {0x0, 0x0, 0xc0000629f0?})
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/common/route/route.go:83 +0x1f6
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000c7e420, {0x39d2540, 0xc001588120}, 0xc00154c100)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/julienschmidt/httprouter/router.go:387 +0x7eb
github.com/prometheus/common/route.(*Router).ServeHTTP(0xc000f02830?, {0x39d2540?, 0xc001588120?}, 0x0?)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/common/route/route.go:126 +0x25
main.main.func6({0x39d2540, 0xc001588120}, 0xc00154c100)
	/go/src/github.com/jacksontj/promxy/cmd/promxy/main.go:465 +0x428
net/http.HandlerFunc.ServeHTTP(0xc000d07380?, {0x39d2540?, 0xc001588120?}, 0xc0011d2310?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000d07380, {0x39d2540, 0xc001588120}, 0xc00154c100)
	/go/src/github.com/jacksontj/promxy/vendor/github.com/julienschmidt/httprouter/router.go:448 +0x602
github.com/jacksontj/promxy/pkg/middleware.(*ProxyHeaders).ServeHTTP(0xc000e0ef30, {0x39d2540, 0xc001588120}, 0xc00297e000)
	/go/src/github.com/jacksontj/promxy/pkg/middleware/headers.go:32 +0x259
github.com/jacksontj/promxy/pkg/logging.(*ApacheLoggingHandler).runHandler(0xc00297e000?, {0x39d2540?, 0xc001588120?}, 0x10?)
	/go/src/github.com/jacksontj/promxy/pkg/logging/logging.go:142 +0x66
github.com/jacksontj/promxy/pkg/logging.(*ApacheLoggingHandler).ServeHTTP(0xc000e0ef60, {0x39d2030, 0xc000c902a0}, 0xc00297e000)
	/go/src/github.com/jacksontj/promxy/pkg/logging/logging.go:165 +0x20d
net/http.serverHandler.ServeHTTP({0xc001f2b110?}, {0x39d2030?, 0xc000c902a0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc002119320, {0x39e1270, 0xc000e0f230})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 355
	/usr/local/go/src/net/http/server.go:3086 +0x5cb

```

Why does this happen?
