### ISSUE TITLE
recording rules not work 

### ISSUE THREAD

**Issue by hashwing** [jacksontj/promxy#74]
set a recording rule:
```yaml
groups
- name: example
    rules:
      - record: query_qps
        expr: irate(http_requests_total{handler="query"}[5m])
```
query `irate(http_requests_total{handler="query"}[5m])` , can find data. 

query `query_qps` , result  `no data`.
