### ISSUE TITLE
Add support for various timeranges associated with ServerGroups

### ISSUE THREAD

**Issue by jacksontj** [jacksontj/promxy#88]
The goal here being to support sending queries to separate stacks of metrics storage based on their "staleness". The prom API unfortunately doesn't expose the `StartTime()` method from the `Storage` -- so we'd need to add config options to set a `time.Duration` offset and duration for each servergroup. Then promxy can add this dimension to its filtering for where to send queries to.

**Comment by jacksontj** [comment]
With the more recent rearch inside servergroup this is a trivial add to make, at this point I just need to decide on the config format. I'm thinking having absolute time is probably not useful -- so I'll set it up as relative times. The config formats I'm thinking of now are:

```
# relative start and end 
time_range:
  start: 3d
  end: 1d

# define only as an offset and duration (offset back from now, duration how much further back)
time_range:
  offset: 1d
  duration: 2d
```

**Comment by jacksontj** [comment]
After some more thought, I'm planning on adding 2 time range options:

```
# for relative offset
relative_time_range:
  start: -3d
  end: -1d


absolute_time_range:
  start: 2009-10-10 23:00:00 +0000 UTC m=+0.000000001
  end: 2009-11-10 23:00:00 +0000 UTC m=+0.000000001
```

And for both of these if the window is invalid (e.g. start after end) there'll be an error.
